# WM and GM distribution in the pediatric spinal cord

This jupyter notebook includes scripts to generate figures related to the white matter and gray matter distribution in the pediatric spinal cord.

In [21]:
import os
import pandas as pd
import json
import yaml
import re
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px
import webbrowser
import statsmodels.formula.api as smf

### Load config file to get path to dataset

In [22]:
# Load config file
with open('../../config/config_preprocessing.yaml' , 'r') as file:
    config = yaml.safe_load(file)

# Get data path from config file
path_data = config['path_data']

### Get the `participants.tsv` file from the dataset

In [23]:
# Get path to participants.tsv file
participants_tsv = pd.read_csv(os.path.join(path_data, 'participants.tsv'), sep='\t')
participants_tsv

    participant_id  age sex    group scan_series    height     weight
0          sub-101   17   M  control    complete  1.778004  68.038864
1          sub-102   15   F  control    complete  1.625603  52.163129
2          sub-103   15   M  control    complete  1.651003  54.431091
3          sub-104   15   F  control    complete  1.625603  52.163129
4          sub-105   13   M  control    complete  1.524000  35.381000
..             ...  ...  ..      ...         ...       ...        ...
131        sub-235   13   M  control  incomplete       NaN        NaN
132        sub-236   13   M  control    complete       NaN        NaN
133        sub-237   13   M  control    complete       NaN        NaN
134        sub-238   15   F  control    complete       NaN        NaN
135        sub-239    6   F  control    complete       NaN        NaN

[136 rows x 7 columns]

## Dataframe of subjects included in the pipeline analysis

The following dataframe contains only the subjects that were included in this pipeline analysis.

In [24]:
def get_list_of_subjects_to_include(contrast, path_data, missing_data_subjects):
    """
    This function takes an image contrast (T2w, dwi, etc.), a path to a dataset, and a list of subjects with missing data,
    and returns a list of subjects to include in the analysis.

    The dataset needs to be in BIDS format, and the function will look for the participants.tsv file to get the list of subjects.
    The dataset should also contain an `exclude.yml` file that lists subjects to exclude from the analysis.
    """

    # Get the `participants.tsv` file and read it into a dataframe
    participants_tsv = pd.read_csv(os.path.join(path_data, 'participants.tsv'), sep='\t')

    # Get all subject IDs from the participants.tsv
    all_subjects = participants_tsv['participant_id'].tolist()

    # Get list of subjects to exclude from the analysis from the `exclude.yml` file
    with open(os.path.join(path_data, 'exclude.yml'), 'r') as file:
        exclude_yml = yaml.safe_load(file)

    exclude_t2star_key = exclude_yml.get(contrast, []) # Extract subjects under contrast key
    exclude_subjects = sorted(set(re.match(r"(sub-\d+)", entry).group(1) for entry in exclude_t2star_key if re.match(r"(sub-\d+)", entry))) # Extract the subject ID 

    # Add the list of subjects with missing data to the exclude_subjects list
    exclude_subjects.extend(missing_data_subjects)
    
    # Remove duplicates (if any), sort and print the list of subjects to exclude from the analysis
    exclude_subjects = sorted(set(exclude_subjects))
    print(f'subjects to exclude : {exclude_subjects}')

    # Compute the list of subjects to include in the analysis 
    include_subjects = [sub for sub in all_subjects if sub not in exclude_subjects]

    # Convert the list of included subjects to a dataframe
    include_subjects = participants_tsv[participants_tsv['participant_id'].isin(include_subjects)]

    return include_subjects

In [25]:
# List of subjects with missing t2star data or missing T2w rootlet segmentation
missing_t2star_subjects = [
                        "sub-109",
                        "sub-125",
                        "sub-136",
                        "sub-152",
                        "sub-159",
                        "sub-174",
                        "sub-198",
                        "sub-200",
                        "sub-205",
                        "sub-211",
                        "sub-213",
                        "sub-221",
                        "sub-234",
                        "sub-235"]

missing_rootlets_subjects = ["sub-108", "sub-110", "sub-111", "sub-121", "sub-127", "sub-133", "sub-136", "sub-141", "sub-150", 
                             "sub-159", "sub-160", "sub-161", "sub-163", "sub-165", "sub-167", "sub-168", "sub-169", 
                             "sub-170", "sub-177", "sub-179", "sub-186", "sub-190", "sub-191", "sub-193", "sub-198", 
                             "sub-203", "sub-208", "sub-209", "sub-210", "sub-211", "sub-213", "sub-214"]

# Combine both lists of missing subjects
missing_subjects = missing_t2star_subjects + missing_rootlets_subjects
print(missing_subjects)

# Get the list of subjects to include in the analysis
include_t2star_subjects = get_list_of_subjects_to_include('t2starw', path_data, missing_subjects)
include_t2star_subjects.to_csv(os.path.join('../tables/GM_WM_distribution/include_t2star_subjects.csv'), sep='\t', index=False)

print(include_t2star_subjects.shape[0], "subjects to include in the analysis")
print(f"\n list of subjects to include : \n {include_t2star_subjects['participant_id'].tolist()}")

include_t2star_subjects

['sub-109', 'sub-125', 'sub-136', 'sub-152', 'sub-159', 'sub-174', 'sub-198', 'sub-200', 'sub-205', 'sub-211', 'sub-213', 'sub-221', 'sub-234', 'sub-235', 'sub-108', 'sub-110', 'sub-111', 'sub-121', 'sub-127', 'sub-133', 'sub-136', 'sub-141', 'sub-150', 'sub-159', 'sub-160', 'sub-161', 'sub-163', 'sub-165', 'sub-167', 'sub-168', 'sub-169', 'sub-170', 'sub-177', 'sub-179', 'sub-186', 'sub-190', 'sub-191', 'sub-193', 'sub-198', 'sub-203', 'sub-208', 'sub-209', 'sub-210', 'sub-211', 'sub-213', 'sub-214']
subjects to exclude : ['sub-106', 'sub-107', 'sub-108', 'sub-109', 'sub-110', 'sub-111', 'sub-120', 'sub-121', 'sub-124', 'sub-125', 'sub-127', 'sub-133', 'sub-136', 'sub-139', 'sub-141', 'sub-144', 'sub-150', 'sub-152', 'sub-154', 'sub-159', 'sub-160', 'sub-161', 'sub-163', 'sub-165', 'sub-167', 'sub-168', 'sub-169', 'sub-170', 'sub-171', 'sub-172', 'sub-174', 'sub-177', 'sub-179', 'sub-181', 'sub-186', 'sub-188', 'sub-189', 'sub-190', 'sub-191', 'sub-193', 'sub-194', 'sub-196', 'sub-198', 'sub-199', 'sub-200', 'sub-203', 'sub-204', 'sub-205', 'sub-207', 'sub-208', 'sub-209', 'sub-210', 'sub-211', 'sub-212', 'sub-213', 'sub-214', 'sub-221', 'sub-225', 'sub-228', 'sub-231', 'sub-232', 'sub-234', 'sub-235', 'sub-236', 'sub-238', 'sub-239']
70 subjects to include in the analysis

 list of subjects to include :
 ['sub-101', 'sub-102', 'sub-103', 'sub-104', 'sub-105', 'sub-112', 'sub-113', 'sub-114', 'sub-115', 'sub-116', 'sub-117', 'sub-118', 'sub-119', 'sub-122', 'sub-123', 'sub-126', 'sub-128', 'sub-129', 'sub-130', 'sub-131', 'sub-132', 'sub-134', 'sub-135', 'sub-137', 'sub-138', 'sub-140', 'sub-142', 'sub-143', 'sub-145', 'sub-146', 'sub-147', 'sub-148', 'sub-149', 'sub-151', 'sub-153', 'sub-155', 'sub-156', 'sub-158', 'sub-162', 'sub-164', 'sub-166', 'sub-173', 'sub-175', 'sub-176', 'sub-178', 'sub-180', 'sub-182', 'sub-183', 'sub-184', 'sub-185', 'sub-192', 'sub-197', 'sub-201', 'sub-202', 'sub-206', 'sub-215', 'sub-216', 'sub-217', 'sub-218', 'sub-219', 'sub-220', 'sub-222', 'sub-223', 'sub-224', 'sub-226', 'sub-227', 'sub-229', 'sub-230', 'sub-233', 'sub-237']

    participant_id  age sex    group scan_series    height     weight
0          sub-101   17   M  control    complete  1.778004  68.038864
1          sub-102   15   F  control    complete  1.625603  52.163129
2          sub-103   15   M  control    complete  1.651003  54.431091
3          sub-104   15   F  control    complete  1.625603  52.163129
4          sub-105   13   M  control    complete  1.524000  35.381000
..             ...  ...  ..      ...         ...       ...        ...
123        sub-227   11   F  control    complete       NaN        NaN
125        sub-229   10   M  control    complete       NaN        NaN
126        sub-230   11   F  control    complete       NaN        NaN
129        sub-233   16   M  control    complete       NaN        NaN
133        sub-237   13   M  control    complete       NaN        NaN

[70 rows x 7 columns]

## Plot demographics

This function plots the age and sex distribution of the subjects included in a pipeline analysis, according to the include list generated above.

In [26]:
def plot_demographics(df):
    """
    This function plots the demographic information of participants, given a dataframe with the list of subjects to include in the analysis.
    """

    # Sort by sex
    df_M = df[df['sex'] == 'M']
    df_F = df[df['sex'] == 'F']

    # Round down age to nearest month 
    df['age'] = np.floor(df['age']) 

    # Create subplot
    fig = make_subplots(rows=1, cols=1)

    # Add histogram for female subjects
    fig.add_trace(go.Histogram(
        x=df_F['age'], 
        name='F', 
        marker=dict(color= "#D19D88"),
        opacity=1.0,
        legendgroup='F',
        ),
        row=1, col=1
    )

    # Add histogram for male subjects
    fig.add_trace(go.Histogram(
        x=df_M['age'], 
        name='M', 
        
        marker=dict(color="#5C8EA1"),
        opacity=1.0,
        legendgroup='M',
        ), 
        row=1, col=1
    )

    # Define age tick range
    tick_vals = list(range(6, 18)) 

    # Update layout
    fig.update_layout(
        width=900,
        height=500,
        font=dict(family='Arial', size=20, color='black'), 
        legend=dict(
            orientation="h", 
            yanchor="bottom", 
            y=1.0, 
            xanchor="center",  
            x=0.5,
        ),
        xaxis=dict(
            range=[5, 18],  # Set x-axis range from 6 to 17
        ),
        plot_bgcolor='white',
        barmode='stack',
        bargap=0.3,  
        xaxis_title='Age (years)',
        xaxis_title_font=dict(family='Arial', size=20, weight='bold'),
        yaxis_title='Number of Subjects',
        yaxis_title_font=dict(family='Arial', size=20, weight='bold'),
        xaxis_title_standoff=50, 
    )

    fig.update_xaxes(
        tickmode='array',
        tickvals=tick_vals,
        showgrid=False,
        gridwidth=1
    )

    fig.update_yaxes(
        showgrid=True,             # Horizontal grid lines
        gridcolor='lightgrey',
        gridwidth=1
    )

    # Set bin size to 1 year
    fig.update_traces(xbins=dict(size=1))

    fig.show()

In [27]:
# Plot demographics for included subjects in DWI analysis
plot_demographics(include_t2star_subjects)

# Create a dataframe for GM, WM and SC CSA (all subjects combined)

In [28]:
# Path to WM, GM and SC CSA (one file per subject)
CSA_base_folder = "../tables/GM_WM_distribution/"
labels = ['WM', 'GM', 'SC']

WMGM_distribution_df = {}

for label in labels:
    label_folder = os.path.join(CSA_base_folder, label)
    label_dfs = []

    if not os.path.exists(label_folder):
        print(f"Folder not found: {label_folder}")
        continue
    
    for filename in os.listdir(label_folder):
        if filename.endswith(".csv"):
            if not any(sub in filename for sub in include_t2star_subjects['participant_id'].tolist()):
                continue  # Skip subjects not in the include list
            subject_path = os.path.join(label_folder, filename)
            df = pd.read_csv(subject_path)
            subject_id = filename.split("_")[0]  # Or use regex for more robust parsing
            df["participant_id"] = subject_id
            label_dfs.append(df)
    
    if label_dfs:
        WMGM_distribution_df[label] = pd.concat(label_dfs, ignore_index=True)
    else:
        print(f"Warning: No CSV files found for label {label}")
        WMGM_distribution_df[label] = pd.DataFrame()

# Add age and sex to DTI metric dataframe
for label in WMGM_distribution_df:
    WMGM_distribution_df[label] = WMGM_distribution_df[label].merge(include_t2star_subjects, on="participant_id", how="left")

In [29]:
# Save combined WM, GM and SC CSA dataframes to csv files

df_WM = WMGM_distribution_df['WM']
#WMGM_distribution_df['WM'].to_csv('../tables/GM_WM_distribution/WM/WM_CSA.csv', index=False)

df_GM = WMGM_distribution_df['GM']
#WMGM_distribution_df['GM'].to_csv('../tables/GM_WM_distribution/GM/GM_CSA.csv', index=False)

df_SC = WMGM_distribution_df['SC']
#WMGM_distribution_df['SC'].to_csv('../tables/GM_WM_distribution/SC/SC_CSA.csv', index=False)

In [30]:
df_SC

,Timestamp,SCT Version,Filename,Slice (I->S),VertLevel,DistancePMJ,MEAN(area),STD(area),MEAN(angle_AP),STD(angle_AP),...,STD(solidity),SUM(length),Spinal_Level,participant_id,age,sex,group,scan_series,height,weight
0,2026-06-10 09:40:06,7.1,/Users/samuellestonge/Documents/datasets/phila...,5:6,NaN,NaN,67.001564,2.557635,1.444220,0.034301,...,0.000470,10.018033,4,sub-162,12,F,control,complete,NaN,NaN
1,2026-06-10 09:38:49,7.1,/Users/samuellestonge/Documents/datasets/phila...,11:12,NaN,NaN,72.179111,1.186971,4.031516,0.422219,...,0.000521,10.129460,4,sub-101,17,M,control,complete,1.778004,68.038864
2,2026-06-10 09:38:51,7.1,/Users/samuellestonge/Documents/datasets/phila...,8:10,NaN,NaN,67.536966,3.031030,2.172522,0.535057,...,0.003387,15.066830,5,sub-101,17,M,control,complete,1.778004,68.038864
3,2026-06-10 09:38:55,7.1,/Users/samuellestonge/Documents/datasets/phila...,2:3,NaN,NaN,71.307166,0.649065,-0.477210,0.077407,...,0.000754,10.009539,7,sub-101,17,M,control,complete,1.778004,68.038864
4,2026-06-10 09:38:57,7.1,/Users/samuellestonge/Documents/datasets/phila...,2:14,NaN,NaN,71.548554,3.525123,2.065735,2.211153,...,0.006772,65.460274,all_levels,sub-101,17,M,control,complete,1.778004,68.038864
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,2026-06-10 09:40:45,7.1,/Users/samuellestonge/Documents/datasets/phila...,8:10,NaN,NaN,77.610264,0.841413,-1.446457,0.154392,...,0.003597,15.010931,4,sub-192,17,F,control,complete,NaN,NaN
366,2026-06-10 09:40:47,7.1,/Users/samuellestonge/Documents/datasets/phila...,5:7,NaN,NaN,83.605233,0.726333,-1.047910,0.063400,...,0.003492,15.085114,5,sub-192,17,F,control,complete,NaN,NaN
367,2026-06-10 09:40:52,7.1,/Users/samuellestonge/Documents/datasets/phila...,0:1,NaN,NaN,82.826425,2.773693,-1.181580,0.064162,...,0.004734,10.299462,7,sub-192,17,F,control,complete,NaN,NaN
368,2026-06-10 09:40:54,7.1,/Users/samuellestonge/Documents/datasets/phila...,0:13,NaN,NaN,81.093328,3.876910,-1.381628,0.469623,...,0.004165,70.751724,all_levels,sub-192,17,F,control,complete,NaN,NaN
369,2026-06-10 09:40:49,7.1,/Users/samuellestonge/Documents/datasets/phila...,2:4,NaN,NaN,85.245847,2.070007,-0.985133,0.029938,...,0.000873,15.260948,6,sub-192,17,F,control,complete,NaN,NaN

# Merge WM and GM dataframes and compute WM/GM ratio, GM/SC ratio and WM/SC ratio

In [31]:
# Merge WM and GM dataframes
df_GM_WM = df_WM.merge(
    df_GM,
    on=['participant_id', 'Spinal_Level', 'age', 'sex'], 
    suffixes=('_WM', '_GM')
)

# Add "_SC" suffix to df_SC columns except for the merge keys
df_SC = df_SC.rename(columns={col: f"{col}_SC" for col in df_SC.columns if col not in ['participant_id', 'Spinal_Level', 'age', 'sex']})

# Merge SC dataframe to the dataframe with WM and GM
df_GM_WM_SC = df_GM_WM.merge(
    df_SC, 
    on=['participant_id', 'Spinal_Level', 'age', 'sex']
)

df_GM_WM_SC.columns

Index(['Timestamp_WM', 'SCT Version_WM', 'Filename_WM', 'Slice (I->S)_WM',
       'VertLevel_WM', 'DistancePMJ_WM', 'MEAN(area)_WM', 'STD(area)_WM',
       'MEAN(angle_AP)_WM', 'STD(angle_AP)_WM', 'MEAN(angle_RL)_WM',
       'STD(angle_RL)_WM', 'MEAN(diameter_AP)_WM', 'STD(diameter_AP)_WM',
       'MEAN(diameter_RL)_WM', 'STD(diameter_RL)_WM', 'MEAN(eccentricity)_WM',
       'STD(eccentricity)_WM', 'MEAN(orientation)_WM', 'STD(orientation)_WM',
       'MEAN(solidity)_WM', 'STD(solidity)_WM', 'SUM(length)_WM',
       'Spinal_Level', 'participant_id', 'age', 'sex', 'group_WM',
       'scan_series_WM', 'height_WM', 'weight_WM', 'Timestamp_GM',
       'SCT Version_GM', 'Filename_GM', 'Slice (I->S)_GM', 'VertLevel_GM',
       'DistancePMJ_GM', 'MEAN(area)_GM', 'STD(area)_GM', 'MEAN(angle_AP)_GM',
       'STD(angle_AP)_GM', 'MEAN(angle_RL)_GM', 'STD(angle_RL)_GM',
       'MEAN(diameter_AP)_GM', 'STD(diameter_AP)_GM', 'MEAN(diameter_RL)_GM',
       'STD(diameter_RL)_GM', 'MEAN(eccentricity)_GM', 'STD(eccentricity)_GM',
       'MEAN(orientation)_GM', 'STD(orientation)_GM', 'MEAN(solidity)_GM',
       'STD(solidity)_GM', 'SUM(length)_GM', 'group_GM', 'scan_series_GM',
       'height_GM', 'weight_GM', 'Timestamp_SC', 'SCT Version_SC',
       'Filename_SC', 'Slice (I->S)_SC', 'VertLevel_SC', 'DistancePMJ_SC',
       'MEAN(area)_SC', 'STD(area)_SC', 'MEAN(angle_AP)_SC',
       'STD(angle_AP)_SC', 'MEAN(angle_RL)_SC', 'STD(angle_RL)_SC',
       'MEAN(diameter_AP)_SC', 'STD(diameter_AP)_SC', 'MEAN(diameter_RL)_SC',
       'STD(diameter_RL)_SC', 'MEAN(eccentricity)_SC', 'STD(eccentricity)_SC',
       'MEAN(orientation)_SC', 'STD(orientation)_SC', 'MEAN(solidity)_SC',
       'STD(solidity)_SC', 'SUM(length)_SC', 'group_SC', 'scan_series_SC',
       'height_SC', 'weight_SC'],
      dtype='object')

In [32]:
df_GM_WM_SC

,Timestamp_WM,SCT Version_WM,Filename_WM,Slice (I->S)_WM,VertLevel_WM,DistancePMJ_WM,MEAN(area)_WM,STD(area)_WM,MEAN(angle_AP)_WM,STD(angle_AP)_WM,...,STD(eccentricity)_SC,MEAN(orientation)_SC,STD(orientation)_SC,MEAN(solidity)_SC,STD(solidity)_SC,SUM(length)_SC,group_SC,scan_series_SC,height_SC,weight_SC
0,2026-06-10 09:39:57,7.1,/Users/samuellestonge/Documents/datasets/phila...,2:4,NaN,NaN,61.300003,4.364803,-0.350735,0.014703,...,0.008509,1.995023,0.562156,0.979268,0.002620,15.008764,control,complete,NaN,NaN
1,2026-06-10 09:39:59,7.1,/Users/samuellestonge/Documents/datasets/phila...,0:1,NaN,NaN,62.816458,0.877176,-0.476359,0.044769,...,0.003553,2.499936,0.566569,0.978932,0.002765,10.010993,control,complete,NaN,NaN
2,2026-06-10 09:40:01,7.1,/Users/samuellestonge/Documents/datasets/phila...,0:12,NaN,NaN,60.387836,2.690938,-0.632134,0.327167,...,0.025083,3.150648,0.897597,0.978726,0.003867,65.060729,control,complete,NaN,NaN
3,2026-06-10 09:39:54,7.1,/Users/samuellestonge/Documents/datasets/phila...,5:7,NaN,NaN,58.827611,1.698180,-0.435720,0.059625,...,0.006297,3.455386,0.381938,0.973531,0.002948,15.001372,control,complete,NaN,NaN
4,2026-06-10 09:39:52,7.1,/Users/samuellestonge/Documents/datasets/phila...,8:9,NaN,NaN,60.227878,0.260861,-0.702973,0.073091,...,0.001233,4.214141,0.058587,0.980217,0.001369,10.003936,control,complete,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,2026-06-10 09:40:11,7.1,/Users/samuellestonge/Documents/datasets/phila...,0:1,NaN,NaN,59.564615,1.807090,1.149085,0.276341,...,0.000795,1.254638,0.120186,0.981586,0.006244,10.032520,control,complete,NaN,NaN
366,2026-06-10 09:40:07,7.1,/Users/samuellestonge/Documents/datasets/phila...,3:5,NaN,NaN,59.579088,1.441259,2.555740,0.214142,...,0.004854,1.647690,0.023690,0.976035,0.006220,15.022596,control,complete,NaN,NaN
367,2026-06-10 09:40:14,7.1,/Users/samuellestonge/Documents/datasets/phila...,0:11,NaN,NaN,56.654399,4.658251,2.386701,0.643941,...,0.005047,2.334083,1.220728,0.978858,0.005565,60.223873,control,complete,NaN,NaN
368,2026-06-10 09:40:05,7.1,/Users/samuellestonge/Documents/datasets/phila...,6:7,NaN,NaN,56.028857,0.466785,2.966345,0.026762,...,0.004263,2.429449,0.462182,0.982297,0.001640,10.039870,control,complete,NaN,NaN
369,2026-06-10 09:40:02,7.1,/Users/samuellestonge/Documents/datasets/phila...,8:11,NaN,NaN,51.122661,1.031887,2.711901,0.222513,...,0.004906,3.721959,0.953212,0.977988,0.005161,20.124046,control,complete,NaN,NaN

In [33]:
# Compute WM/GM ratio
df_GM_WM_SC['GM_WM_ratio'] = df_GM_WM_SC['MEAN(area)_GM'] / df_GM_WM_SC['MEAN(area)_WM'].values

# Compute GM/SC ratio and GM percentage
df_GM_WM_SC['GM_SC_ratio'] = df_GM_WM_SC['MEAN(area)_GM'] / df_GM_WM_SC['MEAN(area)_SC'].values
df_GM_WM_SC['GM_percentage'] = df_GM_WM_SC['GM_SC_ratio']*100

# Compute WM/SC ratio and WM percentage
df_GM_WM_SC['WM_SC_ratio'] = df_GM_WM_SC['MEAN(area)_WM'] / df_GM_WM_SC['MEAN(area)_SC'].values
df_GM_WM_SC['WM_percentage'] = df_GM_WM_SC['WM_SC_ratio']*100

## Plot GM, WM and SC CSA with age using spinal levels

In [34]:
def plot_CSA_all_labels(df):
    """
    Plots CSA (WM, GM, SC) across vertebral levels as a function of age.
    Fits OLS regressions for each label and displays confidence intervals and p-values.

    Args:
        df (pd.DataFrame): DataFrame containing columns:
            'age', 'sex', 'Spinal_Level', and 'MEAN(area)_WM', 'MEAN(area)_GM', 'MEAN(area)_SC'.
    """

    df = df.copy()

    vert_levels = ['3', '4', '5', '6', '7', 'all_levels']
    labels = ['WM', 'GM', 'SC']

    colors = {
    'WM': 'rgba(31, 119, 180, 1)',   # blue
    'GM': 'rgba(255, 127, 14, 1)',   # orange
    'SC': 'rgba(44, 160, 44, 1)',    # green
    }
    
    ci_colors = {
        'WM': 'rgba(31, 119, 180, 0.2)',
        'GM': 'rgba(255, 127, 14, 0.2)',
        'SC': 'rgba(44, 160, 44, 0.2)',
    }

    fig = make_subplots(
        rows=len(vert_levels),
        cols=1,
        shared_xaxes=False,
        shared_yaxes=False,
        vertical_spacing=0.04,
        horizontal_spacing=0.1
    )

    for row_idx, vert in enumerate(vert_levels, start=1):
        data = df[df['Spinal_Level'] == vert].copy()
        print(data)
        if data.empty:
            continue

        x_range = np.linspace(data['age'].min(), data['age'].max(), 100)

        # Get the metric column name for each label
        for label in labels:
            metric_col = f'MEAN(area)_{label}'
            if metric_col not in data.columns:
                continue

            # Fit OLS model
            ols_model = smf.ols(formula=f'Q("{metric_col}") ~ age', data=data).fit()
            pred_df = pd.DataFrame({'age': x_range})
            pred = ols_model.get_prediction(pred_df).summary_frame(alpha=0.05)

            y_fit = pred['mean']
            ci_lower = pred['mean_ci_lower']
            ci_upper = pred['mean_ci_upper']

            # Scatter data
            fig.add_trace(
                go.Scatter(
                    x=data['age'],
                    y=data[metric_col],
                    mode='markers',
                    marker=dict(color=colors[label], size=9, opacity=0.6),
                    name=f'{label} (C{vert})',
                    showlegend=(row_idx == 1)  # show legend only for first subplot
                ),
                row=row_idx, col=1
            )

            # Regression line
            fig.add_trace(
                go.Scatter(
                    x=x_range,
                    y=y_fit,
                    mode='lines',
                    line=dict(color=colors[label], width=2),
                    name=f'{label} fit',
                    showlegend=False
                ),
                row=row_idx, col=1
            )

            # Confidence interval
            fig.add_trace(
                go.Scatter(
                    x=np.concatenate([x_range, x_range[::-1]]),
                    y=np.concatenate([ci_upper, ci_lower[::-1]]),
                    fill='toself',
                    fillcolor=ci_colors[label],
                    line=dict(color='rgba(255,255,255,0)'),
                    hoverinfo='skip',
                    showlegend=False
                ),
                row=row_idx, col=1
            )

            # Store p-values for each label 
            pvals = {}
            for label in labels:
                metric_col = f'MEAN(area)_{label}'
                if metric_col not in data.columns:
                    continue

                ols_model = smf.ols(formula=f'Q("{metric_col}") ~ age', data=data).fit()
                pvals[label] = ols_model.pvalues['age']

            # Build vertical text (stacked)
            text_lines = []
            for label in labels:
                p_value = pvals[label]
                significance = '*' if p_value < 0.05 else ''
                color = 'red' if p_value < 0.05 else 'black'
                text_lines.append(f"<span style='color:{color};'>p-{label} = {p_value:.3f}{significance}</span>")

            # Combine with HTML line breaks for vertical layout
            text_combined = "<br>".join(text_lines)

            # Add annotation box with all p-values
            fig.add_annotation(
            x=0.1,  
            y=1.0,  
            xref="x domain",
            yref="y domain",
            text=text_combined,
            align='left',  # align text within box
            showarrow=False,
            font=dict(size=12, family='Arial', color='black'),
            bgcolor='rgba(255,255,255,0.75)',
            bordercolor='black',
            borderwidth=1.5,
            borderpad=6,
            row=row_idx, col=1
        )


        # Axes
        fig.update_xaxes(
            title_text='Age',
            title_font=dict(size=18, family='Arial', color='black', weight='bold'),
            tickfont=dict(size=16, family='Arial', color='black'),
            tickvals=list(range(6, 18)),
            range=[5, 18],  
            row=row_idx, col=1
        )

        fig.update_yaxes(
            title_text=f'CSA in C{vert} (mm²)',
            title_font=dict(size=20, family='Arial', color='black', weight='bold'),
            tickfont=dict(size=16, family='Arial', color='black'),
            range=[0, 90],
            row=row_idx, col=1
        )

    # Layout
    fig.update_layout(
        height=2200,
        width=600,
        plot_bgcolor='white',
        paper_bgcolor='white',
        legend=dict(
            orientation="h",
            yanchor="bottom",
            y=1.02,
            xanchor="center",
            x=0.5,
            font=dict(size=14)
        )
    )

    fig.show()

In [35]:
df_GM_WM_SC

,Timestamp_WM,SCT Version_WM,Filename_WM,Slice (I->S)_WM,VertLevel_WM,DistancePMJ_WM,MEAN(area)_WM,STD(area)_WM,MEAN(angle_AP)_WM,STD(angle_AP)_WM,...,SUM(length)_SC,group_SC,scan_series_SC,height_SC,weight_SC,GM_WM_ratio,GM_SC_ratio,GM_percentage,WM_SC_ratio,WM_percentage
0,2026-06-10 09:39:57,7.1,/Users/samuellestonge/Documents/datasets/phila...,2:4,NaN,NaN,61.300003,4.364803,-0.350735,0.014703,...,15.008764,control,complete,NaN,NaN,0.275756,0.216149,21.614861,0.783840,78.384000
1,2026-06-10 09:39:59,7.1,/Users/samuellestonge/Documents/datasets/phila...,0:1,NaN,NaN,62.816458,0.877176,-0.476359,0.044769,...,10.010993,control,complete,NaN,NaN,0.253924,0.202449,20.244878,0.797282,79.728152
2,2026-06-10 09:40:01,7.1,/Users/samuellestonge/Documents/datasets/phila...,0:12,NaN,NaN,60.387836,2.690938,-0.632134,0.327167,...,65.060729,control,complete,NaN,NaN,0.251579,0.200998,20.099786,0.798946,79.894647
3,2026-06-10 09:39:54,7.1,/Users/samuellestonge/Documents/datasets/phila...,5:7,NaN,NaN,58.827611,1.698180,-0.435720,0.059625,...,15.001372,control,complete,NaN,NaN,0.269127,0.212057,21.205655,0.787943,78.794290
4,2026-06-10 09:39:52,7.1,/Users/samuellestonge/Documents/datasets/phila...,8:9,NaN,NaN,60.227878,0.260861,-0.702973,0.073091,...,10.003936,control,complete,NaN,NaN,0.250947,0.200596,20.059550,0.799355,79.935485
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
365,2026-06-10 09:40:11,7.1,/Users/samuellestonge/Documents/datasets/phila...,0:1,NaN,NaN,59.564615,1.807090,1.149085,0.276341,...,10.032520,control,complete,NaN,NaN,0.242742,0.195361,19.536141,0.804811,80.481071
366,2026-06-10 09:40:07,7.1,/Users/samuellestonge/Documents/datasets/phila...,3:5,NaN,NaN,59.579088,1.441259,2.555740,0.214142,...,15.022596,control,complete,NaN,NaN,0.254167,0.202664,20.266437,0.797367,79.736709
367,2026-06-10 09:40:14,7.1,/Users/samuellestonge/Documents/datasets/phila...,0:11,NaN,NaN,56.654399,4.658251,2.386701,0.643941,...,60.223873,control,complete,NaN,NaN,0.231178,0.187771,18.777087,0.812236,81.223628
368,2026-06-10 09:40:05,7.1,/Users/samuellestonge/Documents/datasets/phila...,6:7,NaN,NaN,56.028857,0.466785,2.966345,0.026762,...,10.039870,control,complete,NaN,NaN,0.226626,0.184757,18.475715,0.815250,81.525037
369,2026-06-10 09:40:02,7.1,/Users/samuellestonge/Documents/datasets/phila...,8:11,NaN,NaN,51.122661,1.031887,2.711901,0.222513,...,20.124046,control,complete,NaN,NaN,0.208755,0.172682,17.268172,0.827199,82.719878

In [36]:
plot_CSA_all_labels(df_GM_WM_SC)

            Timestamp_WM  SCT Version_WM  \
5    2026-06-10 09:39:50             7.1
11   2026-06-10 09:35:43             7.1
17   2026-06-10 09:38:52             7.1
18   2026-06-10 09:38:49             7.1
24   2026-06-10 09:39:34             7.1
..                   ...             ...
340  2026-06-10 09:39:18             7.1
350  2026-06-10 09:40:55             7.1
353  2026-06-10 09:39:59             7.1
358  2026-06-10 09:35:43             7.1
369  2026-06-10 09:40:02             7.1

                                           Filename_WM Slice (I->S)_WM  \
5    /Users/samuellestonge/Documents/datasets/phila...           10:12
11   /Users/samuellestonge/Documents/datasets/phila...           11:13
17   /Users/samuellestonge/Documents/datasets/phila...           12:14
18   /Users/samuellestonge/Documents/datasets/phila...           11:14
24   /Users/samuellestonge/Documents/datasets/phila...           13:14
..                                                 ...             ...
340  /Users/samuellestonge/Documents/datasets/phila...           11:13
350  /Users/samuellestonge/Documents/datasets/phila...           10:13
353  /Users/samuellestonge/Documents/datasets/phila...           11:13
358  /Users/samuellestonge/Documents/datasets/phila...            9:13
369  /Users/samuellestonge/Documents/datasets/phila...            8:11

     VertLevel_WM  DistancePMJ_WM  MEAN(area)_WM  STD(area)_WM  \
5             NaN             NaN      59.523449      0.960178
11            NaN             NaN      60.567087      2.208685
17            NaN             NaN      54.537264      4.027795
18            NaN             NaN      51.048281      2.750562
24            NaN             NaN      63.254317      3.036252
..            ...             ...            ...           ...
340           NaN             NaN      61.456064     18.437219
350           NaN             NaN      63.344204      1.999449
353           NaN             NaN      59.478389      0.463983
358           NaN             NaN      60.308896      3.504808
369           NaN             NaN      51.122661      1.031887

     MEAN(angle_AP)_WM  STD(angle_AP)_WM  ...  SUM(length)_SC  group_SC  \
5            -1.166573          0.179585  ...       15.035664   control
11            0.574448          0.306361  ...       15.123789   control
17            3.277571          0.480251  ...       15.206685   control
18           -4.152304          0.787842  ...       20.148369   control
24           -1.037004          0.005484  ...       10.180364   control
..                 ...               ...  ...             ...       ...
340           0.374764          0.017773  ...       15.513675   control
350           0.600763          0.311803  ...       20.029883   control
353           8.207483          0.182700  ...       15.280265   control
358           2.505784          1.341970  ...       25.585408   control
369           2.711901          0.222513  ...       20.124046   control

     scan_series_SC  height_SC  weight_SC  GM_WM_ratio  GM_SC_ratio  \
5          complete        NaN        NaN     0.208113     0.172261
11         complete        NaN        NaN     0.211436     0.174497
17         complete   1.676000  61.236000     0.216251     0.177873
18         complete   1.651003  54.431091     0.223945     0.183026
24         complete        NaN        NaN     0.179903     0.152713
..              ...        ...        ...          ...          ...
340        complete        NaN        NaN     0.180612     0.189118
350        complete        NaN        NaN     0.214758     0.176792
353        complete        NaN        NaN     0.208383     0.172371
358        complete        NaN        NaN     0.205149     0.170249
369        complete        NaN        NaN     0.208755     0.172682

     GM_percentage  WM_SC_ratio  WM_percentage
5        17.226126     0.827730      82.772986
11       17.449698     0.825295      82.529534
17       17.787274     0.822528      82.252798
18       18.302606     0.817280      81.727999
24       15.271336     0.848863      84.886347
..             ...          ...            ...
340      18.911757     1.047091     104.709129
350      17.679215     0.823215      82.321473
353      17.237083     0.827182      82.718210
358      17.024877     0.829879      82.987871
369      17.268172     0.827199      82.719878

[61 rows x 90 columns]
            Timestamp_WM  SCT Version_WM  \
4    2026-06-10 09:39:52             7.1
10   2026-06-10 09:35:45             7.1
15   2026-06-10 09:38:54             7.1
21   2026-06-10 09:38:50             7.1
25   2026-06-10 09:39:36             7.1
..                   ...             ...
341  2026-06-10 09:39:20             7.1
346  2026-06-10 09:40:58             7.1
356  2026-06-10 09:40:01             7.1
363  2026-06-10 09:35:44             7.1
368  2026-06-10 09:40:05             7.1

                                           Filename_WM Slice (I->S)_WM  \
4    /Users/samuellestonge/Documents/datasets/phila...             8:9
10   /Users/samuellestonge/Documents/datasets/phila...            8:10
15   /Users/samuellestonge/Documents/datasets/phila...            9:11
21   /Users/samuellestonge/Documents/datasets/phila...            8:10
25   /Users/samuellestonge/Documents/datasets/phila...           10:12
..                                                 ...             ...
341  /Users/samuellestonge/Documents/datasets/phila...            9:10
346  /Users/samuellestonge/Documents/datasets/phila...             8:9
356  /Users/samuellestonge/Documents/datasets/phila...            8:10
363  /Users/samuellestonge/Documents/datasets/phila...               8
368  /Users/samuellestonge/Documents/datasets/phila...             6:7

     VertLevel_WM  DistancePMJ_WM  MEAN(area)_WM  STD(area)_WM  \
4             NaN             NaN      60.227878      0.260861
10            NaN             NaN      54.854543      1.305650
15            NaN             NaN      57.252902      3.654014
21            NaN             NaN      47.438782      1.835056
25            NaN             NaN      61.268959      1.965815
..            ...             ...            ...           ...
341           NaN             NaN      53.642162      1.343391
346           NaN             NaN      60.147434      0.743506
356           NaN             NaN      54.822356      1.491608
363           NaN             NaN      55.671147      0.000000
368           NaN             NaN      56.028857      0.466785

     MEAN(angle_AP)_WM  STD(angle_AP)_WM  ...  SUM(length)_SC  group_SC  \
4            -0.702973          0.073091  ...       10.003936   control
10           -0.721812          0.399416  ...       15.087004   control
15            1.951061          0.243185  ...       15.046978   control
21           -2.211707          0.318964  ...       15.019901   control
25           -0.963584          0.037268  ...       15.057403   control
..                 ...               ...  ...             ...       ...
341           0.600719          0.092981  ...       10.027199   control
346           1.168754          0.039682  ...       10.016762   control
356           7.383401          0.266287  ...       15.161974   control
363           4.782581          0.000000  ...        5.126682   control
368           2.966345          0.026762  ...       10.039870   control

     scan_series_SC  height_SC  weight_SC  GM_WM_ratio  GM_SC_ratio  \
4          complete        NaN        NaN     0.250947     0.200596
10         complete        NaN        NaN     0.262738     0.208065
15         complete   1.676000  61.236000     0.253907     0.202502
21         complete   1.651003  54.431091     0.224628     0.183437
25         complete        NaN        NaN     0.215802     0.177556
..              ...        ...        ...          ...          ...
341        complete        NaN        NaN     0.244362     0.196505
346        complete        NaN        NaN     0.309031     0.236053
356        complete        NaN        NaN     0.244641     0.196482
363        complete        NaN        NaN     0.157664     0.136202
368        complete        NaN        NaN     0.226626     0.184757

     GM_percentage  WM_SC_ratio  WM_percentage
4        20.059550     0.799355      79.935485
10       20.806467     0.791908      79.190819
15       20.250201     0.797543      79.754269
21       18.343720     0.816626      81.662647
25       17.755618     0.822772      82.277217
..             ...          ...            ...
341      19.650545     0.804156      80.415614
346      23.605270     0.763848      76.384817
356      19.648203     0.803144      80.314351
363      13.620155     0.863871      86.387068
368      18.475715     0.815250      81.525037

[61 rows x 90 columns]
            Timestamp_WM  SCT Version_WM  \
3    2026-06-10 09:39:54             7.1
8    2026-06-10 09:35:47             7.1
14   2026-06-10 09:38:56             7.1
20   2026-06-10 09:38:52             7.1
27   2026-06-10 09:39:38             7.1
..                   ...             ...
342  2026-06-10 09:39:23             7.1
347  2026-06-10 09:41:01             7.1
357  2026-06-10 09:40:03             7.1
362  2026-06-10 09:35:46             7.1
366  2026-06-10 09:40:07             7.1

                                           Filename_WM Slice (I->S)_WM  \
3    /Users/samuellestonge/Documents/datasets/phila...             5:7
8    /Users/samuellestonge/Documents/datasets/phila...             6:7
14   /Users/samuellestonge/Documents/datasets/phila...             6:8
20   /Users/samuellestonge/Documents/datasets/phila...             5:7
27   /Users/samuellestonge/Documents/datasets/phila...             7:9
..                                                 ...             ...
342  /Users/samuellestonge/Documents/datasets/phila...             6:8
347  /Users/samuellestonge/Documents/datasets/phila...             6:7
357  /Users/samuellestonge/Documents/datasets/phila...             5:7
362  /Users/samuellestonge/Documents/datasets/phila...             6:7
366  /Users/samuellestonge/Documents/datasets/phila...             3:5

     VertLevel_WM  DistancePMJ_WM  MEAN(area)_WM  STD(area)_WM  \
3             NaN             NaN      58.827611      1.698180
8             NaN             NaN      55.804004      0.768079
14            NaN             NaN      58.387201      0.968191
20            NaN             NaN      53.728778      5.204125
27            NaN             NaN      66.298396      1.850538
..            ...             ...            ...           ...
342           NaN             NaN      56.130355      2.445028
347           NaN             NaN      62.114621      1.986251
357           NaN             NaN      60.290770      2.124967
362           NaN             NaN      53.860084      4.681662
366           NaN             NaN      59.579088      1.441259

     MEAN(angle_AP)_WM  STD(angle_AP)_WM  ...  SUM(length)_SC  group_SC  \
3            -0.435720          0.059625  ...       15.001372   control
8            -2.054715          0.291721  ...       10.035984   control
14            1.499857          0.023234  ...       15.008673   control
20           -1.449031          0.099133  ...       15.005932   control
27           -0.765064          0.071011  ...       15.007817   control
..                 ...               ...  ...             ...       ...
342           1.304421          0.298516  ...       15.048926   control
347           1.195568          0.026275  ...       10.021383   control
357           6.250311          0.350830  ...       15.092876   control
362           5.288535          0.116256  ...       10.191633   control
366           2.555740          0.214142  ...       15.022596   control

     scan_series_SC  height_SC  weight_SC  GM_WM_ratio  GM_SC_ratio  \
3          complete        NaN        NaN     0.269127     0.212057
8          complete        NaN        NaN     0.218759     0.179511
14         complete   1.676000  61.236000     0.283850     0.221104
20         complete   1.651003  54.431091     0.266717     0.210567
27         complete        NaN        NaN     0.254929     0.203126
..              ...        ...        ...          ...          ...
342        complete        NaN        NaN     0.269020     0.211888
347        complete        NaN        NaN     0.258947     0.205664
357        complete        NaN        NaN     0.280182     0.218829
362        complete        NaN        NaN     0.232317     0.188483
366        complete        NaN        NaN     0.254167     0.202664

     GM_percentage  WM_SC_ratio  WM_percentage
3        21.205655     0.787943      78.794290
8        17.951094     0.820590      82.058954
14       22.110414     0.778946      77.894605
20       21.056667     0.789476      78.947593
27       20.312590     0.796796      79.679554
..             ...          ...            ...
342      21.188801     0.787630      78.763019
347      20.566412     0.794231      79.423115
357      21.882937     0.781026      78.102554
362      18.848335     0.811320      81.131984
366      20.266437     0.797367      79.736709

[61 rows x 90 columns]
            Timestamp_WM  SCT Version_WM  \
0    2026-06-10 09:39:57             7.1
6    2026-06-10 09:35:49             7.1
12   2026-06-10 09:38:58             7.1
22   2026-06-10 09:38:54             7.1
29   2026-06-10 09:39:40             7.1
..                   ...             ...
345  2026-06-10 09:39:25             7.1
349  2026-06-10 09:41:05             7.1
355  2026-06-10 09:40:05             7.1
359  2026-06-10 09:35:48             7.1
364  2026-06-10 09:40:09             7.1

                                           Filename_WM Slice (I->S)_WM  \
0    /Users/samuellestonge/Documents/datasets/phila...             2:4
6    /Users/samuellestonge/Documents/datasets/phila...             3:5
12   /Users/samuellestonge/Documents/datasets/phila...             3:5
22   /Users/samuellestonge/Documents/datasets/phila...             2:4
29   /Users/samuellestonge/Documents/datasets/phila...             4:6
..                                                 ...             ...
345  /Users/samuellestonge/Documents/datasets/phila...             4:5
349  /Users/samuellestonge/Documents/datasets/phila...             3:5
355  /Users/samuellestonge/Documents/datasets/phila...             3:4
359  /Users/samuellestonge/Documents/datasets/phila...             4:5
364  /Users/samuellestonge/Documents/datasets/phila...               2

     VertLevel_WM  DistancePMJ_WM  MEAN(area)_WM  STD(area)_WM  \
0             NaN             NaN      61.300003      4.364803
6             NaN             NaN      60.667879      1.829342
12            NaN             NaN      61.028212      2.451873
22            NaN             NaN      55.533542      0.952749
29            NaN             NaN      69.685819      3.818387
..            ...             ...            ...           ...
345           NaN             NaN      58.299568      1.895857
349           NaN             NaN      68.606430      3.759951
355           NaN             NaN      61.500179      1.224447
359           NaN             NaN      53.390303      1.976926
364           NaN             NaN      65.437941      0.000000

     MEAN(angle_AP)_WM  STD(angle_AP)_WM  ...  SUM(length)_SC  group_SC  \
0            -0.350735          0.014703  ...       15.008764   control
6            -3.637636          0.552403  ...       15.042813   control
12            1.925671          0.236313  ...       15.035331   control
22           -1.500651          0.126713  ...       15.013539   control
29           -0.442299          0.104806  ...       15.051669   control
..                 ...               ...  ...             ...       ...
345           2.425337          0.271739  ...       10.106885   control
349           0.844292          0.178258  ...       15.049611   control
355           5.074871          0.258342  ...       10.039656   control
359           5.439926          0.040531  ...       10.089948   control
364           1.894732          0.000000  ...        5.004841   control

     scan_series_SC  height_SC  weight_SC  GM_WM_ratio  GM_SC_ratio  \
0          complete        NaN        NaN     0.275756     0.216149
6          complete        NaN        NaN     0.165746     0.142198
12         complete   1.676000  61.236000     0.269716     0.212429
22         complete   1.651003  54.431091     0.286308     0.222575
29         complete        NaN        NaN     0.243908     0.196017
..              ...        ...        ...          ...          ...
345        complete        NaN        NaN     0.259711     0.206389
349        complete        NaN        NaN     0.244492     0.196452
355        complete        NaN        NaN     0.273532     0.214809
359        complete        NaN        NaN     0.260078     0.206415
364        complete        NaN        NaN     0.225196     0.183809

     GM_percentage  WM_SC_ratio  WM_percentage
0        21.614861     0.783840      78.384000
6        14.219818     0.857929      85.792912
12       21.242868     0.787602      78.760237
22       22.257463     0.777396      77.739619
29       19.601689     0.803652      80.365167
..             ...          ...            ...
345      20.638902     0.794687      79.468663
349      19.645170     0.803511      80.351096
355      21.480886     0.785316      78.531618
359      20.641472     0.793666      79.366597
364      18.380855     0.816216      81.621590

[61 rows x 90 columns]
            Timestamp_WM  SCT Version_WM  \
1    2026-06-10 09:39:59             7.1
7    2026-06-10 09:35:51             7.1
13   2026-06-10 09:38:59             7.1
23   2026-06-10 09:38:56             7.1
28   2026-06-10 09:39:42             7.1
..                   ...             ...
343  2026-06-10 09:39:27             7.1
348  2026-06-10 09:41:09             7.1
354  2026-06-10 09:40:07             7.1
360  2026-06-10 09:35:50             7.1
365  2026-06-10 09:40:11             7.1

                                           Filename_WM Slice (I->S)_WM  \
1    /Users/samuellestonge/Documents/datasets/phila...             0:1
7    /Users/samuellestonge/Documents/datasets/phila...             1:2
13   /Users/samuellestonge/Documents/datasets/phila...             1:2
23   /Users/samuellestonge/Documents/datasets/phila...             0:1
28   /Users/samuellestonge/Documents/datasets/phila...             1:3
..                                                 ...             ...
343  /Users/samuellestonge/Documents/datasets/phila...             1:3
348  /Users/samuellestonge/Documents/datasets/phila...             1:2
354  /Users/samuellestonge/Documents/datasets/phila...             0:2
360  /Users/samuellestonge/Documents/datasets/phila...             1:3
365  /Users/samuellestonge/Documents/datasets/phila...             0:1

     VertLevel_WM  DistancePMJ_WM  MEAN(area)_WM  STD(area)_WM  \
1             NaN             NaN      62.816458      0.877176
7             NaN             NaN      64.440374      2.046984
13            NaN             NaN      61.574490      0.904916
23            NaN             NaN      56.783374      3.878101
28            NaN             NaN      59.603193      5.896786
..            ...             ...            ...           ...
343           NaN             NaN      58.562777      2.528642
348           NaN             NaN      64.157234      1.534372
354           NaN             NaN      58.003858      3.366412
360           NaN             NaN      53.946520      2.650700
365           NaN             NaN      59.564615      1.807090

     MEAN(angle_AP)_WM  STD(angle_AP)_WM  ...  SUM(length)_SC  group_SC  \
1            -0.476359          0.044769  ...       10.010993   control
7            -5.435259          0.383666  ...       10.051628   control
13            2.929284          0.265426  ...       10.052600   control

## Plot GM and WM percentages with respect to age

In [ ]:
def plot_ratio(df, label_1, label_2, y_min, y_max):

    """
    This function plots the ratio between two labels (e.g., GM and WM) across different spinal levels. The ratio is computed as : label_1 / label_2

    Args:
        df (pd.DataFrame): DataFrame containing the data to plot. Must include columns 'age', 'sex', 'VertLevel', and the ratio column. 
        The ratio column should be named as '{label_1}_{label_2}_ratio'.
        label (str): The label we want to plot (in %) ('GM' or 'WM').
    """
    
    df = df.copy()

    # Vertebral levels to plot
    vert_levels = ['3', '4', '5', '6', '7', 'all_levels']

    # Define color of markers 
    color = "#222020"

    # Color for confidence interval
    ci_color = 'rgba(34, 32, 32, 0.35)' 

    fig = make_subplots(
        rows=6,
        cols=1,
        shared_xaxes=False,
        shared_yaxes=False,
        vertical_spacing=0.05,
        horizontal_spacing=0.1
    )

    for row_idx, vert in enumerate(vert_levels, start=1):

        # Filder data according to the VertLevel
        data = df[df['Spinal_Level'] == vert].copy()

        print(data)

        x_range = np.linspace(data['age'].min(), data['age'].max(), 100)
        pred_df = pd.DataFrame({'age': x_range})

        ratio_name = f'{label_1}_{label_2}_ratio'
        ols_formula = f'{ratio_name} ~ age'

        ols_model = smf.ols(formula=ols_formula, data=data)
        ols_results = ols_model.fit()

        # Print OLS results
        print(ols_results.summary())

        pred = ols_results.get_prediction(pred_df)
        pred_summary = pred.summary_frame(alpha=0.05)

        y_fit = pred_summary['mean']
        ci_lower = pred_summary['mean_ci_lower']
        ci_upper = pred_summary['mean_ci_upper']

        # Scatter plot
        fig.add_trace(
            go.Scatter(
                x=data['age'],
                y=data[ratio_name],
                mode='markers',
                marker=dict(color=color, size=11, symbol='circle', opacity=0.8),
                showlegend=False
            ),
            row=row_idx, col=1
        )

        # Fit line
        fig.add_trace(
            go.Scatter(
                x=x_range,
                y=y_fit,
                mode='lines',
                line=dict(color=color, width=2, dash='solid'),
                showlegend=False
            ),
            row=row_idx, col=1
        )

        # Confidence interval
        fig.add_trace(
            go.Scatter(
                x=np.concatenate([x_range, x_range[::-1]]),
                y=np.concatenate([ci_upper, ci_lower[::-1]]),
                fill='toself',
                fillcolor=ci_color,
                line=dict(color='rgba(255,255,255,0)'),
                hoverinfo='skip',
                showlegend=False,
            ),
            row=row_idx, col=1
        )

        # Add p-value as annotation
        p_value = ols_results.pvalues['age']
        significance = ''
        if p_value < 0.05:
            significance = '*'
            font_color='red'
        else:
            font_color='black'
            
        fig.add_annotation(
            x=0.88,  # relative within subplot (0–1)
            y=0.98,  # near the top
            xref="x domain",
            yref="y domain",
            text = f'p-Age = {p_value:.3f} <span style="color:{font_color}">{significance}</span>',
            showarrow=False,
            font=dict(family='Arial', size=16, color='black'),
            bgcolor='rgba(255, 255, 255, 0.7)',
            bordercolor='black',
            borderwidth=1,
            borderpad=4,
            row=row_idx, col=1
        )

        fig.update_xaxes(
                title_text='Age',
                title_font=dict(family='Arial', size=20, color='black', weight='bold'),
                tickfont=dict(family='Arial', size=18),
                tickvals=list(range(6, 18)),
                range=[5, 18],
                row=row_idx, col=1
            )
        
        fig.update_yaxes(
                title_text=f'% {label} in C{vert}',
                title_font=dict(family='Arial', size=20, color='black', weight='bold'),
                tickfont=dict(family='Arial', size=18),
                range=[y_min, y_max],
                row=row_idx, col=1
            )

    # Update layout
    fig.update_layout(
        height=1800,
        width=600,
        plot_bgcolor="#ffffff",
        paper_bgcolor="#ffffff"
    )

    fig.show()

## Plot GM% vs Age

In [40]:
plot_ratio(df_GM_WM_SC, 'GM', 15, 25)

TypeError: plot_ratio() missing 1 required positional argument: 'percent_max'

## Plot WM% vs Age

In [39]:
plot_percentage(df_GM_WM_SC, 'WM', 70, 90)

            Timestamp_WM  SCT Version_WM  \
5    2026-06-10 09:39:50             7.1
11   2026-06-10 09:35:43             7.1
17   2026-06-10 09:38:52             7.1
18   2026-06-10 09:38:49             7.1
24   2026-06-10 09:39:34             7.1
..                   ...             ...
340  2026-06-10 09:39:18             7.1
350  2026-06-10 09:40:55             7.1
353  2026-06-10 09:39:59             7.1
358  2026-06-10 09:35:43             7.1
369  2026-06-10 09:40:02             7.1

                                           Filename_WM Slice (I->S)_WM  \
5    /Users/samuellestonge/Documents/datasets/phila...           10:12
11   /Users/samuellestonge/Documents/datasets/phila...           11:13
17   /Users/samuellestonge/Documents/datasets/phila...           12:14
18   /Users/samuellestonge/Documents/datasets/phila...           11:14
24   /Users/samuellestonge/Documents/datasets/phila...           13:14
..                                                 ...             ...
340  /Users/samuellestonge/Documents/datasets/phila...           11:13
350  /Users/samuellestonge/Documents/datasets/phila...           10:13
353  /Users/samuellestonge/Documents/datasets/phila...           11:13
358  /Users/samuellestonge/Documents/datasets/phila...            9:13
369  /Users/samuellestonge/Documents/datasets/phila...            8:11

     VertLevel_WM  DistancePMJ_WM  MEAN(area)_WM  STD(area)_WM  \
5             NaN             NaN      59.523449      0.960178
11            NaN             NaN      60.567087      2.208685
17            NaN             NaN      54.537264      4.027795
18            NaN             NaN      51.048281      2.750562
24            NaN             NaN      63.254317      3.036252
..            ...             ...            ...           ...
340           NaN             NaN      61.456064     18.437219
350           NaN             NaN      63.344204      1.999449
353           NaN             NaN      59.478389      0.463983
358           NaN             NaN      60.308896      3.504808
369           NaN             NaN      51.122661      1.031887

     MEAN(angle_AP)_WM  STD(angle_AP)_WM  ...  SUM(length)_SC  group_SC  \
5            -1.166573          0.179585  ...       15.035664   control
11            0.574448          0.306361  ...       15.123789   control
17            3.277571          0.480251  ...       15.206685   control
18           -4.152304          0.787842  ...       20.148369   control
24           -1.037004          0.005484  ...       10.180364   control
..                 ...               ...  ...             ...       ...
340           0.374764          0.017773  ...       15.513675   control
350           0.600763          0.311803  ...       20.029883   control
353           8.207483          0.182700  ...       15.280265   control
358           2.505784          1.341970  ...       25.585408   control
369           2.711901          0.222513  ...       20.124046   control

     scan_series_SC  height_SC  weight_SC  GM_WM_ratio  GM_SC_ratio  \
5          complete        NaN        NaN     0.208113     0.172261
11         complete        NaN        NaN     0.211436     0.174497
17         complete   1.676000  61.236000     0.216251     0.177873
18         complete   1.651003  54.431091     0.223945     0.183026
24         complete        NaN        NaN     0.179903     0.152713
..              ...        ...        ...          ...          ...
340        complete        NaN        NaN     0.180612     0.189118
350        complete        NaN        NaN     0.214758     0.176792
353        complete        NaN        NaN     0.208383     0.172371
358        complete        NaN        NaN     0.205149     0.170249
369        complete        NaN        NaN     0.208755     0.172682

     GM_percentage  WM_SC_ratio  WM_percentage
5        17.226126     0.827730      82.772986
11       17.449698     0.825295      82.529534
17       17.787274     0.822528      82.252798
18       18.302606     0.817280      81.727999
24       15.271336     0.848863      84.886347
..             ...          ...            ...
340      18.911757     1.047091     104.709129
350      17.679215     0.823215      82.321473
353      17.237083     0.827182      82.718210
358      17.024877     0.829879      82.987871
369      17.268172     0.827199      82.719878

[61 rows x 90 columns]
                            OLS Regression Results
==============================================================================
Dep. Variable:          WM_percentage   R-squared:                       0.007
Model:                            OLS   Adj. R-squared:                 -0.010
Method:                 Least Squares   F-statistic:                    0.4295
Date:                Wed, 10 Jun 2026   Prob (F-statistic):              0.515
Time:                        11:21:21   Log-Likelihood:                -158.28
No. Observations:                  61   AIC:                             320.6
Df Residuals:                      59   BIC:                             324.8
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     81.1152      2.141     37.887      0.000      76.831      85.399
age            0.1048      0.160      0.655      0.515      -0.215       0.425
==============================================================================
Omnibus:                      106.815   Durbin-Watson:                   1.910
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             3384.931
Skew:                           5.286   Prob(JB):                         0.00
Kurtosis:                      37.928   Cond. No.                         68.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
            Timestamp_WM  SCT Version_WM  \
4    2026-06-10 09:39:52             7.1
10   2026-06-10 09:35:45             7.1
15   2026-06-10 09:38:54             7.1
21   2026-06-10 09:38:50             7.1
25   2026-06-10 09:39:36             7.1
..                   ...             ...
341  2026-06-10 09:39:20             7.1
346  2026-06-10 09:40:58             7.1
356  2026-06-10 09:40:01             7.1
363  2026-06-10 09:35:44             7.1
368  2026-06-10 09:40:05             7.1

                                           Filename_WM Slice (I->S)_WM  \
4    /Users/samuellestonge/Documents/datasets/phila...             8:9
10   /Users/samuellestonge/Documents/datasets/phila...            8:10
15   /Users/samuellestonge/Documents/datasets/phila...            9:11
21   /Users/samuellestonge/Documents/datasets/phila...            8:10
25   /Users/samuellestonge/Documents/datasets/phila...           10:12
..                                                 ...             ...
341  /Users/samuellestonge/Documents/datasets/phila...            9:10
346  /Users/samuellestonge/Documents/datasets/phila...             8:9
356  /Users/samuellestonge/Documents/datasets/phila...            8:10
363  /Users/samuellestonge/Documents/datasets/phila...               8
368  /Users/samuellestonge/Documents/datasets/phila...             6:7

     VertLevel_WM  DistancePMJ_WM  MEAN(area)_WM  STD(area)_WM  \
4             NaN             NaN      60.227878      0.260861
10            NaN             NaN      54.854543      1.305650
15            NaN             NaN      57.252902      3.654014
21            NaN             NaN      47.438782      1.835056
25            NaN             NaN      61.268959      1.965815
..            ...             ...            ...           ...
341           NaN             NaN      53.642162      1.343391
346           NaN             NaN      60.147434      0.743506
356           NaN             NaN      54.822356      1.491608
363           NaN             NaN      55.671147      0.000000
368           NaN             NaN      56.028857      0.466785

     MEAN(angle_AP)_WM  STD(angle_AP)_WM  ...  SUM(length)_SC  group_SC  \
4            -0.702973          0.073091  ...       10.003936   control
10           -0.721812          0.399416  ...       15.087004   control
15            1.951061          0.243185  ...       15.046978   control
21           -2.211707          0.318964  ...       15.019901   control
25           -0.963584          0.037268  ...       15.057403   control
..                 ...               ...  ...             ...       ...
341           0.600719          0.092981  ...       10.027199   control
346           1.168754          0.039682  ...       10.016762   control
356           7.383401          0.266287  ...       15.161974   control
363           4.782581          0.000000  ...        5.126682   control
368           2.966345          0.026762  ...       10.039870   control

     scan_series_SC  height_SC  weight_SC  GM_WM_ratio  GM_SC_ratio  \
4          complete        NaN        NaN     0.250947     0.200596
10         complete        NaN        NaN     0.262738     0.208065
15         complete   1.676000  61.236000     0.253907     0.202502
21         complete   1.651003  54.431091     0.224628     0.183437
25         complete        NaN        NaN     0.215802     0.177556
..              ...        ...        ...          ...          ...
341        complete        NaN        NaN     0.244362     0.196505
346        complete        NaN        NaN     0.309031     0.236053
356        complete        NaN        NaN     0.244641     0.196482
363        complete        NaN        NaN     0.157664     0.136202
368        complete        NaN        NaN     0.226626     0.184757

     GM_percentage  WM_SC_ratio  WM_percentage
4        20.059550     0.799355      79.935485
10       20.806467     0.791908      79.190819
15       20.250201     0.797543      79.754269
21       18.343720     0.816626      81.662647
25       17.755618     0.822772      82.277217
..             ...          ...            ...
341      19.650545     0.804156      80.415614
346      23.605270     0.763848      76.384817
356      19.648203     0.803144      80.314351
363      13.620155     0.863871      86.387068
368      18.475715     0.815250      81.525037

[61 rows x 90 columns]
                            OLS Regression Results
==============================================================================
Dep. Variable:          WM_percentage   R-squared:                       0.007
Model:                            OLS   Adj. R-squared:                 -0.009
Method:                 Least Squares   F-statistic:                    0.4363
Date:                Wed, 10 Jun 2026   Prob (F-statistic):              0.511
Time:                        11:21:21   Log-Likelihood:                -176.30
No. Observations:                  61   AIC:                             356.6
Df Residuals:                      59   BIC:                             360.8
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     79.3798      2.877     27.592      0.000      73.623      85.137
age            0.1419      0.215      0.661      0.511      -0.288       0.572
==============================================================================
Omnibus:                       73.449   Durbin-Watson:                   2.165
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              613.777
Skew:                           3.500   Prob(JB):                    5.25e-134
Kurtosis:                      16.874   Cond. No.                         68.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
            Timestamp_WM  SCT Version_WM  \
3    2026-06-10 09:39:54             7.1
8    2026-06-10 09:35:47             7.1
14   2026-06-10 09:38:56             7.1
20   2026-06-10 09:38:52             7.1
27   2026-06-10 09:39:38             7.1
..                   ...             ...
342  2026-06-10 09:39:23             7.1
347  2026-06-10 09:41:01             7.1
357  2026-06-10 09:40:03             7.1
362  2026-06-10 09:35:46             7.1
366  2026-06-10 09:40:07             7.1

                                           Filename_WM Slice (I->S)_WM  \
3    /Users/samuellestonge/Documents/datasets/phila...             5:7
8    /Users/samuellestonge/Documents/datasets/phila...             6:7
14   /Users/samuellestonge/Documents/datasets/phila...             6:8
20   /Users/samuellestonge/Documents/datasets/phila...             5:7
27   /Users/samuellestonge/Documents/datasets/phila...             7:9
..                                                 ...             ...
342  /Users/samuellestonge/Documents/datasets/phila...             6:8
347  /Users/samuellestonge/Documents/datasets/phila...             6:7
357  /Users/samuellestonge/Documents/datasets/phila...             5:7
362  /Users/samuellestonge/Documents/datasets/phila...             6:7
366  /Users/samuellestonge/Documents/datasets/phila...             3:5

     VertLevel_WM  DistancePMJ_WM  MEAN(area)_WM  STD(area)_WM  \
3             NaN             NaN      58.827611      1.698180
8             NaN             NaN      55.804004      0.768079
14            NaN             NaN      58.387201      0.968191
20            NaN             NaN      53.728778      5.204125
27            NaN             NaN      66.298396      1.850538
..            ...             ...            ...           ...
342           NaN             NaN      56.130355      2.445028
347           NaN             NaN      62.114621      1.986251
357           NaN             NaN      60.290770      2.124967
362           NaN             NaN      53.860084      4.681662
366           NaN             NaN      59.579088      1.441259

     MEAN(angle_AP)_WM  STD(angle_AP)_WM  ...  SUM(length)_SC  group_SC  \
3            -0.435720          0.059625  ...       15.001372   control
8            -2.054715          0.291721  ...       10.035984   control
14            1.499857          0.023234  ...       15.008673   control
20           -1.449031          0.099133  ...       15.005932   control
27           -0.765064          0.071011  ...       15.007817   control
..                 ...               ...  ...             ...       ...
342           1.304421          0.298516  ...       15.048926   control
347           1.195568          0.026275  ...       10.021383   control
357           6.250311          0.350830  ...       15.092876   control
362           5.288535          0.116256  ...       10.191633   control
366           2.555740          0.214142  ...       15.022596   control

     scan_series_SC  height_SC  weight_SC  GM_WM_ratio  GM_SC_ratio  \
3          complete        NaN        NaN     0.269127     0.212057
8          complete        NaN        NaN     0.218759     0.179511
14         complete   1.676000  61.236000     0.283850     0.221104
20         complete   1.651003  54.431091     0.266717     0.210567
27         complete        NaN        NaN     0.254929     0.203126
..              ...        ...        ...          ...          ...
342        complete        NaN        NaN     0.269020     0.211888
347        complete        NaN        NaN     0.258947     0.205664
357        complete        NaN        NaN     0.280182     0.218829
362        complete        NaN        NaN     0.232317     0.188483
366        complete        NaN        NaN     0.254167     0.202664

     GM_percentage  WM_SC_ratio  WM_percentage
3        21.205655     0.787943      78.794290
8        17.951094     0.820590      82.058954
14       22.110414     0.778946      77.894605
20       21.056667     0.789476      78.947593
27       20.312590     0.796796      79.679554
..             ...          ...            ...
342      21.188801     0.787630      78.763019
347      20.566412     0.794231      79.423115
357      21.882937     0.781026      78.102554
362      18.848335     0.811320      81.131984
366      20.266437     0.797367      79.736709

[61 rows x 90 columns]
                            OLS Regression Results
==============================================================================
Dep. Variable:          WM_percentage   R-squared:                       0.006
Model:                            OLS   Adj. R-squared:                 -0.011
Method:                 Least Squares   F-statistic:                    0.3573
Date:                Wed, 10 Jun 2026   Prob (F-statistic):              0.552
Time:                        11:21:21   Log-Likelihood:                -174.86
No. Observations:                  61   AIC:                             353.7
Df Residuals:                      59   BIC:                             357.9
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     81.4095      2.810     28.976      0.000      75.788      87.031
age           -0.1254      0.210     -0.598      0.552      -0.545       0.294
==============================================================================
Omnibus:                       91.758   Durbin-Watson:                   1.330
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1499.439
Skew:                           4.455   Prob(JB):                         0.00
Kurtosis:                      25.596   Cond. No.                         68.3
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
            Timestamp_WM  SCT Version_WM  \
0    2026-06-10 09:39:57             7.1
6    2026-06-10 09:35:49             7.1
12   2026-06-10 09:38:58             7.1
22   2026-06-10 09:38:54             7.1
29   2026-06-10 09:39:40             7.1
..                   ...             ...
345  2026-06-10 09:39:25             7.1
349  2026-06-10 09:41:05             7.1
355  2026-06-10 09:40:05             7.1
359  2026-06-10 09:35:48             7.1
364  2026-06-10 09:40:09             7.1

                                           Filename_WM Slice (I->S)_WM  \
0    /Users/samuellestonge/Documents/datasets/phila...             2:4
6    /Users/samuellestonge/Documents/datasets/phila...             3:5
12   /Users/samuellestonge/Documents/datasets/phila...             3:5
22   /Users/samuellestonge/Documents/datasets/phila...             2:4
29   /Users/samuellestonge/Documents/datasets/phila...             4:6
..                                                 ...             ...
345  /Users/samuellestonge/Documents/datasets/phila...             4:5
349  /Users/samuellestonge/Documents/datasets/phila...             3:5
355  /Users/samuellestonge/Documents/datasets/phila...             3:4
359  /Users/samuellestonge/Documents/datasets/phila...             4:5
364  /Users/samuellestonge/Documents/datasets/phila...               2

     VertLevel_WM  DistancePMJ_WM  MEAN(area)_WM  STD(area)_WM  \
0             NaN             NaN      61.300003      4.364803
6             NaN             NaN      60.667879      1.829342
12            NaN             NaN      61.028212      2.451873