# WM and GM distribution in the pediatric spinal cord

This jupyter notebook includes scripts to generate figures related to the white matter and gray matter distribution in the pediatric spinal cord.

In [3]:
import os
import pandas as pd
import json
import yaml
import re
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px
import webbrowser
import statsmodels.formula.api as smf

### Load config file to get path to dataset

In [4]:
# Load config file
with open('../../config/config_preprocessing.yaml' , 'r') as file:
    config = yaml.safe_load(file)

# Get data path from config file
path_data = config['path_data']

### Get the `participants.tsv` file from the dataset

In [5]:
# Get path to participants.tsv file
participants_tsv = pd.read_csv(os.path.join(path_data, 'participants.tsv'), sep='\t')
participants_tsv

    participant_id  age sex    group scan_series    height     weight
0          sub-101   17   M  control    complete  1.778004  68.038864
1          sub-102   15   F  control    complete  1.625603  52.163129
2          sub-103   15   M  control    complete  1.651003  54.431091
3          sub-104   15   F  control    complete  1.625603  52.163129
4          sub-105   13   M  control    complete  1.524000  35.381000
..             ...  ...  ..      ...         ...       ...        ...
110        sub-214    6   M  control    complete       NaN        NaN
111        sub-215   16   F  control    complete       NaN        NaN
112        sub-216   15   F  control    complete       NaN        NaN
113        sub-217   15   M  control    complete       NaN        NaN
114        sub-218   17   F  control    complete       NaN        NaN

[115 rows x 7 columns]

## Dataframe of subjects included in the pipeline analysis

The following dataframe contains only the subjects that were included in this pipeline analysis.

In [6]:
def get_list_of_subjects_to_include(contrast, path_data, missing_data_subjects):
    """
    This function takes an image contrast (T2w, dwi, etc.), a path to a dataset, and a list of subjects with missing data,
    and returns a list of subjects to include in the analysis.

    The dataset needs to be in BIDS format, and the function will look for the participants.tsv file to get the list of subjects.
    The dataset should also contain an `exclude.yml` file that lists subjects to exclude from the analysis.
    """

    # Get the `participants.tsv` file and read it into a dataframe
    participants_tsv = pd.read_csv(os.path.join(path_data, 'participants.tsv'), sep='\t')

    # Get all subject IDs from the participants.tsv
    all_subjects = participants_tsv['participant_id'].tolist()

    # Get list of subjects to exclude from the analysis from the `exclude.yml` file
    with open(os.path.join(path_data, 'exclude.yml'), 'r') as file:
        exclude_yml = yaml.safe_load(file)

    exclude_t2star_key = exclude_yml.get(contrast, []) # Extract subjects under contrast key
    exclude_subjects = sorted(set(re.match(r"(sub-\d+)", entry).group(1) for entry in exclude_t2star_key if re.match(r"(sub-\d+)", entry))) # Extract the subject ID 

    # Add the list of subjects with missing data to the exclude_subjects list
    exclude_subjects.extend(missing_data_subjects)
    
    # Remove duplicates (if any), sort and print the list of subjects to exclude from the analysis
    exclude_subjects = sorted(set(exclude_subjects))
    print(f'subjects to exclude : {exclude_subjects}')

    # Compute the list of subjects to include in the analysis 
    include_subjects = [sub for sub in all_subjects if sub not in exclude_subjects]

    # Convert the list of included subjects to a dataframe
    include_subjects = participants_tsv[participants_tsv['participant_id'].isin(include_subjects)]

    return include_subjects

In [7]:
# List of subjects with missing t2star data or missing T2w rootlet segmentation
missing_t2star_subjects = [
                        "sub-109",
                        "sub-125",
                        "sub-136",
                        "sub-152",
                        "sub-159",
                        "sub-174",
                        "sub-198",
                        "sub-200",
                        "sub-205",
                        "sub-211",
                        "sub-213"]

missing_rootlets_subjects = ["sub-108", "sub-110", "sub-111", "sub-121", "sub-127", "sub-133", "sub-136", "sub-141", "sub-150", 
                             "sub-159", "sub-160", "sub-161", "sub-163", "sub-165", "sub-167", "sub-168", "sub-169", 
                             "sub-170", "sub-177", "sub-179", "sub-186", "sub-190", "sub-191", "sub-193", "sub-198", 
                             "sub-203", "sub-208", "sub-209", "sub-210", "sub-211", "sub-213", "sub-214"]

# Combine both lists of missing subjects
missing_subjects = missing_t2star_subjects + missing_rootlets_subjects
print(missing_subjects)

# Get the list of subjects to include in the analysis
include_t2star_subjects = get_list_of_subjects_to_include('t2starw', path_data, missing_subjects)
include_t2star_subjects.to_csv(os.path.join('../tables/GM_WM_distribution/include_t2star_subjects.csv'), sep='\t', index=False)

print(include_t2star_subjects.shape[0], "subjects to include in the analysis")
print(f"\n list of subjects to include : \n {include_t2star_subjects['participant_id'].tolist()}")

include_t2star_subjects

['sub-109', 'sub-125', 'sub-136', 'sub-152', 'sub-159', 'sub-174', 'sub-198', 'sub-200', 'sub-205', 'sub-211', 'sub-213', 'sub-108', 'sub-110', 'sub-111', 'sub-121', 'sub-127', 'sub-133', 'sub-136', 'sub-141', 'sub-150', 'sub-159', 'sub-160', 'sub-161', 'sub-163', 'sub-165', 'sub-167', 'sub-168', 'sub-169', 'sub-170', 'sub-177', 'sub-179', 'sub-186', 'sub-190', 'sub-191', 'sub-193', 'sub-198', 'sub-203', 'sub-208', 'sub-209', 'sub-210', 'sub-211', 'sub-213', 'sub-214']
subjects to exclude : ['sub-106', 'sub-107', 'sub-108', 'sub-109', 'sub-110', 'sub-111', 'sub-120', 'sub-121', 'sub-124', 'sub-125', 'sub-127', 'sub-133', 'sub-136', 'sub-139', 'sub-141', 'sub-144', 'sub-150', 'sub-152', 'sub-154', 'sub-159', 'sub-160', 'sub-161', 'sub-163', 'sub-165', 'sub-167', 'sub-168', 'sub-169', 'sub-170', 'sub-171', 'sub-172', 'sub-174', 'sub-177', 'sub-179', 'sub-181', 'sub-186', 'sub-188', 'sub-189', 'sub-190', 'sub-191', 'sub-193', 'sub-194', 'sub-196', 'sub-198', 'sub-199', 'sub-200', 'sub-203', 'sub-204', 'sub-205', 'sub-207', 'sub-208', 'sub-209', 'sub-210', 'sub-211', 'sub-212', 'sub-213', 'sub-214']
59 subjects to include in the analysis

 list of subjects to include :
 ['sub-101', 'sub-102', 'sub-103', 'sub-104', 'sub-105', 'sub-112', 'sub-113', 'sub-114', 'sub-115', 'sub-116', 'sub-117', 'sub-118', 'sub-119', 'sub-122', 'sub-123', 'sub-126', 'sub-128', 'sub-129', 'sub-130', 'sub-131', 'sub-132', 'sub-134', 'sub-135', 'sub-137', 'sub-138', 'sub-140', 'sub-142', 'sub-143', 'sub-145', 'sub-146', 'sub-147', 'sub-148', 'sub-149', 'sub-151', 'sub-153', 'sub-155', 'sub-156', 'sub-158', 'sub-162', 'sub-164', 'sub-166', 'sub-173', 'sub-175', 'sub-176', 'sub-178', 'sub-180', 'sub-182', 'sub-183', 'sub-184', 'sub-185', 'sub-192', 'sub-197', 'sub-201', 'sub-202', 'sub-206', 'sub-215', 'sub-216', 'sub-217', 'sub-218']

    participant_id  age sex    group scan_series    height     weight
0          sub-101   17   M  control    complete  1.778004  68.038864
1          sub-102   15   F  control    complete  1.625603  52.163129
2          sub-103   15   M  control    complete  1.651003  54.431091
3          sub-104   15   F  control    complete  1.625603  52.163129
4          sub-105   13   M  control    complete  1.524000  35.381000
11         sub-112   16   F  control    complete  1.676000  61.236000
12         sub-113   14   F  control    complete  1.676403  72.574788
13         sub-114   14   F  control    complete  1.574803  46.266428
14         sub-115   13   F  control    complete  1.753000  72.576000
15         sub-116   15   F  control    complete  1.676403  61.234978
16         sub-117   12   F  control    complete  1.524003  43.091281
17         sub-118    9   F  control    complete  1.422403  31.751470
18         sub-119   16   F  control    complete  1.498603  38.555356
21         sub-122   16   M  control    complete  1.778004  68.038864
22         sub-123   12   F  control    complete  1.524003  43.091281
25         sub-126   11   F  control    complete       NaN        NaN
27         sub-128   11   F  control    complete       NaN        NaN
28         sub-129   10   F  control    complete       NaN        NaN
29         sub-130   16   M  control    complete       NaN        NaN
30         sub-131   15   F  control    complete       NaN        NaN
31         sub-132   17   M  control    complete       NaN        NaN
33         sub-134   14   F  control    complete       NaN        NaN
34         sub-135   11   M  control    complete       NaN        NaN
36         sub-137   10   M  control  incomplete       NaN        NaN
37         sub-138   10   F  control    complete       NaN        NaN
39         sub-140   15   M  control    complete       NaN        NaN
41         sub-142   12   M  control    complete       NaN        NaN
42         sub-143   10   F  control    complete       NaN        NaN
44         sub-145   16   M  control    complete       NaN        NaN
45         sub-146   11   F  control    complete       NaN        NaN
46         sub-147   13   F  control    complete       NaN        NaN
47         sub-148   15   F  control    complete       NaN        NaN
48         sub-149   16   F  control    complete       NaN        NaN
50         sub-151   16   M  control    complete       NaN        NaN
52         sub-153   15   F  control    complete       NaN        NaN
54         sub-155   16   M  control    complete       NaN        NaN
55         sub-156   16   M  control    complete       NaN        NaN
56         sub-158   10   F  control  incomplete       NaN        NaN
60         sub-162   12   F  control    complete       NaN        NaN
62         sub-164   12   M  control    complete       NaN        NaN
64         sub-166   13   M  control    complete       NaN        NaN
71         sub-173    6   F  control    complete       NaN        NaN
73         sub-175   14   M  control    complete       NaN        NaN
74         sub-176   12   F  control    complete       NaN        NaN
76         sub-178   13   M  control    complete       NaN        NaN
78         sub-180    9   F  control    complete       NaN        NaN
80         sub-182   17   M  control    complete       NaN        NaN
81         sub-183   13   F  control    complete       NaN        NaN
82         sub-184   16   F  control    complete       NaN        NaN
83         sub-185   12   F  control    complete       NaN        NaN
89         sub-192   17   F  control    complete       NaN        NaN
93         sub-197    9   M  control    complete       NaN        NaN
97         sub-201    8   M  control    complete       NaN        NaN
98         sub-202   16   F  control    complete       NaN        NaN
102        sub-206   11   M  control    complete       NaN        NaN
111        sub-215   16   F  control    complete       NaN        NaN
112        sub-216   15   F  control    complete       NaN        NaN
113        sub-217   15   M  control    complete       NaN        NaN
114        sub-218   17   F  control    complete       NaN        NaN

## Plot demographics

This function plots the age and sex distribution of the subjects included in a pipeline analysis, according to the include list generated above.

In [8]:
def plot_demographics(df):
    """
    This function plots the demographic information of participants, given a dataframe with the list of subjects to include in the analysis.
    """

    # Sort by sex
    df_M = df[df['sex'] == 'M']
    df_F = df[df['sex'] == 'F']

    # Round down age to nearest month 
    df['age'] = np.floor(df['age']) 

    # Create subplot
    fig = make_subplots(rows=1, cols=1)

    # Add histogram for female subjects
    fig.add_trace(go.Histogram(
        x=df_F['age'], 
        name='F', 
        marker=dict(color= "#D19D88"),
        opacity=1.0,
        legendgroup='F',
        ),
        row=1, col=1
    )

    # Add histogram for male subjects
    fig.add_trace(go.Histogram(
        x=df_M['age'], 
        name='M', 
        
        marker=dict(color="#5C8EA1"),
        opacity=1.0,
        legendgroup='M',
        ), 
        row=1, col=1
    )

    # Define age tick range
    tick_vals = list(range(6, 18)) 

    # Update layout
    fig.update_layout(
        width=900,
        height=500,
        font=dict(family='Arial', size=20, color='black'), 
        legend=dict(
            orientation="h", 
            yanchor="bottom", 
            y=1.0, 
            xanchor="center",  
            x=0.5,
        ),
        xaxis=dict(
            range=[5, 18],  # Set x-axis range from 6 to 17
        ),
        plot_bgcolor='white',
        barmode='stack',
        bargap=0.3,  
        xaxis_title='Age (years)',
        xaxis_title_font=dict(family='Arial', size=20, weight='bold'),
        yaxis_title='Number of Subjects',
        yaxis_title_font=dict(family='Arial', size=20, weight='bold'),
        xaxis_title_standoff=50, 
    )

    fig.update_xaxes(
        tickmode='array',
        tickvals=tick_vals,
        showgrid=False,
        gridwidth=1
    )

    fig.update_yaxes(
        showgrid=True,             # Horizontal grid lines
        gridcolor='lightgrey',
        gridwidth=1
    )

    # Set bin size to 1 year
    fig.update_traces(xbins=dict(size=1))

    fig.show()

In [9]:
# Plot demographics for included subjects in DWI analysis
plot_demographics(include_t2star_subjects)

# Create a dataframe for GM, WM and SC CSA (all subjects combined)

In [10]:
# Path to WM, GM and SC CSA (one file per subject)
CSA_base_folder = "../tables/GM_WM_distribution/"
labels = ['WM', 'GM', 'SC']

WMGM_distribution_df = {}

for label in labels:
    label_folder = os.path.join(CSA_base_folder, label)
    label_dfs = []

    if not os.path.exists(label_folder):
        print(f"Folder not found: {label_folder}")
        continue
    
    for filename in os.listdir(label_folder):
        if filename.endswith(".csv"):
            if not any(sub in filename for sub in include_t2star_subjects['participant_id'].tolist()):
                continue  # Skip subjects not in the include list
            subject_path = os.path.join(label_folder, filename)
            df = pd.read_csv(subject_path)
            subject_id = filename.split("_")[0]  # Or use regex for more robust parsing
            df["participant_id"] = subject_id
            label_dfs.append(df)
    
    if label_dfs:
        WMGM_distribution_df[label] = pd.concat(label_dfs, ignore_index=True)
    else:
        print(f"Warning: No CSV files found for label {label}")
        WMGM_distribution_df[label] = pd.DataFrame()

# Add age and sex to DTI metric dataframe
for label in WMGM_distribution_df:
    WMGM_distribution_df[label] = WMGM_distribution_df[label].merge(include_t2star_subjects, on="participant_id", how="left")

In [11]:
# Save combined WM, GM and SC CSA dataframes to csv files

df_WM = WMGM_distribution_df['WM']
#WMGM_distribution_df['WM'].to_csv('../tables/GM_WM_distribution/WM/WM_CSA.csv', index=False)

df_GM = WMGM_distribution_df['GM']
#WMGM_distribution_df['GM'].to_csv('../tables/GM_WM_distribution/GM/GM_CSA.csv', index=False)

df_SC = WMGM_distribution_df['SC']
#WMGM_distribution_df['SC'].to_csv('../tables/GM_WM_distribution/SC/SC_CSA.csv', index=False)

In [12]:
df_SC

,Timestamp,SCT Version,Filename,Slice (I->S),VertLevel,DistancePMJ,MEAN(area),STD(area),MEAN(angle_AP),STD(angle_AP),...,STD(solidity),SUM(length),Spinal_Level,participant_id,age,sex,group,scan_series,height,weight
0,2025-12-10 18:44:13,7.1,/Users/samuellestonge/Documents/datasets/phila...,11:12,NaN,NaN,72.179111,1.186971,4.031516,0.422219,...,0.000521,10.129460,4,sub-101,17,M,control,complete,1.778004,68.038864
1,2025-12-10 18:44:15,7.1,/Users/samuellestonge/Documents/datasets/phila...,8:9,NaN,NaN,69.154645,2.435172,1.838687,0.308366,...,0.002410,10.032133,5,sub-101,17,M,control,complete,1.778004,68.038864
2,2025-12-10 18:44:19,7.1,/Users/samuellestonge/Documents/datasets/phila...,2:4,NaN,NaN,71.784415,0.858132,-0.374105,0.158922,...,0.008304,15.010303,7,sub-101,17,M,control,complete,1.778004,68.038864
3,2025-12-10 18:44:22,7.1,/Users/samuellestonge/Documents/datasets/phila...,0:14,NaN,NaN,70.037673,5.336779,1.705948,2.253598,...,0.007193,75.486837,all_levels,sub-101,17,M,control,complete,1.778004,68.038864
4,2025-12-10 18:44:17,7.1,/Users/samuellestonge/Documents/datasets/phila...,4:7,NaN,NaN,71.976263,1.471804,0.372680,0.433353,...,0.011229,20.006747,6,sub-101,17,M,control,complete,1.778004,68.038864
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319,2025-12-10 18:46:30,7.1,/Users/samuellestonge/Documents/datasets/phila...,8:9,NaN,NaN,78.070709,0.652638,-1.348959,0.085074,...,0.002081,10.006980,4,sub-192,17,F,control,complete,NaN,NaN
320,2025-12-10 18:46:32,7.1,/Users/samuellestonge/Documents/datasets/phila...,5:6,NaN,NaN,84.024032,0.514938,-1.006352,0.029121,...,0.000809,10.071111,5,sub-192,17,F,control,complete,NaN,NaN
321,2025-12-10 18:46:36,7.1,/Users/samuellestonge/Documents/datasets/phila...,0:2,NaN,NaN,83.331412,2.374644,-1.129854,0.089976,...,0.004373,15.410141,7,sub-192,17,F,control,complete,NaN,NaN
322,2025-12-10 18:46:38,7.1,/Users/samuellestonge/Documents/datasets/phila...,0:14,NaN,NaN,81.124770,3.747298,-1.479061,0.582021,...,0.004056,75.838370,all_levels,sub-192,17,F,control,complete,NaN,NaN
323,2025-12-10 18:46:34,7.1,/Users/samuellestonge/Documents/datasets/phila...,2:3,NaN,NaN,83.814134,0.527251,-0.999547,0.026853,...,0.001056,10.197024,6,sub-192,17,F,control,complete,NaN,NaN

# Merge WM and GM dataframes and compute WM/GM ratio, GM/SC ratio and WM/SC ratio

In [13]:
# Merge WM and GM dataframes
df_GM_WM = df_WM.merge(
    df_GM,
    on=['participant_id', 'Spinal_Level', 'age', 'sex'], 
    suffixes=('_WM', '_GM')
)

# Add "_SC" suffix to df_SC columns except for the merge keys
df_SC = df_SC.rename(columns={col: f"{col}_SC" for col in df_SC.columns if col not in ['participant_id', 'Spinal_Level', 'age', 'sex']})

# Merge SC dataframe to the dataframe with WM and GM
df_GM_WM_SC = df_GM_WM.merge(
    df_SC, 
    on=['participant_id', 'Spinal_Level', 'age', 'sex']
)

df_GM_WM_SC.columns

Index(['Timestamp_WM', 'SCT Version_WM', 'Filename_WM', 'Slice (I->S)_WM',
       'VertLevel_WM', 'DistancePMJ_WM', 'MEAN(area)_WM', 'STD(area)_WM',
       'MEAN(angle_AP)_WM', 'STD(angle_AP)_WM', 'MEAN(angle_RL)_WM',
       'STD(angle_RL)_WM', 'MEAN(diameter_AP)_WM', 'STD(diameter_AP)_WM',
       'MEAN(diameter_RL)_WM', 'STD(diameter_RL)_WM', 'MEAN(eccentricity)_WM',
       'STD(eccentricity)_WM', 'MEAN(orientation)_WM', 'STD(orientation)_WM',
       'MEAN(solidity)_WM', 'STD(solidity)_WM', 'SUM(length)_WM',
       'Spinal_Level', 'participant_id', 'age', 'sex', 'group_WM',
       'scan_series_WM', 'height_WM', 'weight_WM', 'Timestamp_GM',
       'SCT Version_GM', 'Filename_GM', 'Slice (I->S)_GM', 'VertLevel_GM',
       'DistancePMJ_GM', 'MEAN(area)_GM', 'STD(area)_GM', 'MEAN(angle_AP)_GM',
       'STD(angle_AP)_GM', 'MEAN(angle_RL)_GM', 'STD(angle_RL)_GM',
       'MEAN(diameter_AP)_GM', 'STD(diameter_AP)_GM', 'MEAN(diameter_RL)_GM',
       'STD(diameter_RL)_GM', 'MEAN(eccentricity)_GM', 'STD(eccentricity)_GM',
       'MEAN(orientation)_GM', 'STD(orientation)_GM', 'MEAN(solidity)_GM',
       'STD(solidity)_GM', 'SUM(length)_GM', 'group_GM', 'scan_series_GM',
       'height_GM', 'weight_GM', 'Timestamp_SC', 'SCT Version_SC',
       'Filename_SC', 'Slice (I->S)_SC', 'VertLevel_SC', 'DistancePMJ_SC',
       'MEAN(area)_SC', 'STD(area)_SC', 'MEAN(angle_AP)_SC',
       'STD(angle_AP)_SC', 'MEAN(angle_RL)_SC', 'STD(angle_RL)_SC',
       'MEAN(diameter_AP)_SC', 'STD(diameter_AP)_SC', 'MEAN(diameter_RL)_SC',
       'STD(diameter_RL)_SC', 'MEAN(eccentricity)_SC', 'STD(eccentricity)_SC',
       'MEAN(orientation)_SC', 'STD(orientation)_SC', 'MEAN(solidity)_SC',
       'STD(solidity)_SC', 'SUM(length)_SC', 'group_SC', 'scan_series_SC',
       'height_SC', 'weight_SC'],
      dtype='object')

In [14]:
df_GM_WM_SC

,Timestamp_WM,SCT Version_WM,Filename_WM,Slice (I->S)_WM,VertLevel_WM,DistancePMJ_WM,MEAN(area)_WM,STD(area)_WM,MEAN(angle_AP)_WM,STD(angle_AP)_WM,...,STD(eccentricity)_SC,MEAN(orientation)_SC,STD(orientation)_SC,MEAN(solidity)_SC,STD(solidity)_SC,SUM(length)_SC,group_SC,scan_series_SC,height_SC,weight_SC
0,2025-12-10 18:45:24,7.1,/Users/samuellestonge/Documents/datasets/phila...,2:4,NaN,NaN,61.300003,4.364803,-0.350735,0.014703,...,0.008509,1.995023,0.562156,0.979268,0.002620,15.008764,control,complete,NaN,NaN
1,2025-12-10 18:45:26,7.1,/Users/samuellestonge/Documents/datasets/phila...,0:1,NaN,NaN,62.816458,0.877176,-0.476359,0.044769,...,0.003553,2.499936,0.566569,0.978932,0.002765,10.010993,control,complete,NaN,NaN
2,2025-12-10 18:45:28,7.1,/Users/samuellestonge/Documents/datasets/phila...,0:14,NaN,NaN,60.378424,2.527243,-0.788086,0.503706,...,0.033108,3.187131,0.913102,0.979576,0.004313,75.129071,control,complete,NaN,NaN
3,2025-12-10 18:45:22,7.1,/Users/samuellestonge/Documents/datasets/phila...,5:6,NaN,NaN,59.992678,0.503572,-0.397000,0.028898,...,0.000487,3.715167,0.127890,0.974351,0.003319,10.001129,control,complete,NaN,NaN
4,2025-12-10 18:45:20,7.1,/Users/samuellestonge/Documents/datasets/phila...,8,NaN,NaN,60.488738,0.000000,-0.629882,0.000000,...,0.000000,4.155554,0.000000,0.978848,0.000000,5.001030,control,complete,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319,2025-12-10 18:45:50,7.1,/Users/samuellestonge/Documents/datasets/phila...,0:1,NaN,NaN,61.776319,2.105611,0.887651,0.136309,...,0.015578,1.829327,0.255434,0.978058,0.001201,10.266154,control,complete,NaN,NaN
320,2025-12-10 18:45:46,7.1,/Users/samuellestonge/Documents/datasets/phila...,5:6,NaN,NaN,55.147478,2.192907,1.410996,0.031612,...,0.006898,1.616578,0.913722,0.983062,0.000470,10.018033,control,complete,NaN,NaN
321,2025-12-10 18:45:48,7.1,/Users/samuellestonge/Documents/datasets/phila...,3:4,NaN,NaN,51.678180,0.801226,1.403146,0.035537,...,0.007518,0.809444,0.373462,0.982552,0.002861,10.013795,control,complete,NaN,NaN
322,2025-12-10 18:45:54,7.1,/Users/samuellestonge/Documents/datasets/phila...,0:14,NaN,NaN,55.052726,3.662056,0.909184,0.552296,...,0.028503,1.655772,0.696326,0.979056,0.003945,65.590981,control,complete,NaN,NaN
323,2025-12-10 18:45:45,7.1,/Users/samuellestonge/Documents/datasets/phila...,7:10,NaN,NaN,54.800750,1.303002,0.885455,0.297919,...,0.014815,1.982984,0.605022,0.976301,0.003961,20.159814,control,complete,NaN,NaN

In [15]:
# Compute WM/GM ratio
df_GM_WM_SC['GM_WM_ratio'] = df_GM_WM_SC['MEAN(area)_GM'] / df_GM_WM_SC['MEAN(area)_WM'].values

# Compute GM/SC ratio and GM percentage
df_GM_WM_SC['GM_SC_ratio'] = df_GM_WM_SC['MEAN(area)_GM'] / df_GM_WM_SC['MEAN(area)_SC'].values
df_GM_WM_SC['GM_percentage'] = df_GM_WM_SC['GM_SC_ratio']*100

# Compute WM/SC ratio and WM percentage
df_GM_WM_SC['WM_SC_ratio'] = df_GM_WM_SC['MEAN(area)_WM'] / df_GM_WM_SC['MEAN(area)_SC'].values
df_GM_WM_SC['WM_percentage'] = df_GM_WM_SC['WM_SC_ratio']*100

## Plot GM, WM and SC CSA with age using spinal levels

In [16]:
def plot_CSA_all_labels(df):
    """
    Plots CSA (WM, GM, SC) across vertebral levels as a function of age.
    Fits OLS regressions for each label and displays confidence intervals and p-values.

    Args:
        df (pd.DataFrame): DataFrame containing columns:
            'age', 'sex', 'Spinal_Level', and 'MEAN(area)_WM', 'MEAN(area)_GM', 'MEAN(area)_SC'.
    """

    df = df.copy()

    vert_levels = ['3', '4', '5', '6', '7', 'all_levels']
    labels = ['WM', 'GM', 'SC']

    colors = {
    'WM': 'rgba(31, 119, 180, 1)',   # blue
    'GM': 'rgba(255, 127, 14, 1)',   # orange
    'SC': 'rgba(44, 160, 44, 1)',    # green
    }
    
    ci_colors = {
        'WM': 'rgba(31, 119, 180, 0.2)',
        'GM': 'rgba(255, 127, 14, 0.2)',
        'SC': 'rgba(44, 160, 44, 0.2)',
    }

    fig = make_subplots(
        rows=len(vert_levels),
        cols=1,
        shared_xaxes=False,
        shared_yaxes=False,
        vertical_spacing=0.04,
        horizontal_spacing=0.1
    )

    for row_idx, vert in enumerate(vert_levels, start=1):
        data = df[df['Spinal_Level'] == vert].copy()
        print(data)
        if data.empty:
            continue

        x_range = np.linspace(data['age'].min(), data['age'].max(), 100)

        # Get the metric column name for each label
        for label in labels:
            metric_col = f'MEAN(area)_{label}'
            if metric_col not in data.columns:
                continue

            # Fit OLS model
            ols_model = smf.ols(formula=f'Q("{metric_col}") ~ age', data=data).fit()
            pred_df = pd.DataFrame({'age': x_range})
            pred = ols_model.get_prediction(pred_df).summary_frame(alpha=0.05)

            y_fit = pred['mean']
            ci_lower = pred['mean_ci_lower']
            ci_upper = pred['mean_ci_upper']

            # Scatter data
            fig.add_trace(
                go.Scatter(
                    x=data['age'],
                    y=data[metric_col],
                    mode='markers',
                    marker=dict(color=colors[label], size=9, opacity=0.6),
                    name=f'{label} (C{vert})',
                    showlegend=(row_idx == 1)  # show legend only for first subplot
                ),
                row=row_idx, col=1
            )

            # Regression line
            fig.add_trace(
                go.Scatter(
                    x=x_range,
                    y=y_fit,
                    mode='lines',
                    line=dict(color=colors[label], width=2),
                    name=f'{label} fit',
                    showlegend=False
                ),
                row=row_idx, col=1
            )

            # Confidence interval
            fig.add_trace(
                go.Scatter(
                    x=np.concatenate([x_range, x_range[::-1]]),
                    y=np.concatenate([ci_upper, ci_lower[::-1]]),
                    fill='toself',
                    fillcolor=ci_colors[label],
                    line=dict(color='rgba(255,255,255,0)'),
                    hoverinfo='skip',
                    showlegend=False
                ),
                row=row_idx, col=1
            )

            # Store p-values for each label 
            pvals = {}
            for label in labels:
                metric_col = f'MEAN(area)_{label}'
                if metric_col not in data.columns:
                    continue

                ols_model = smf.ols(formula=f'Q("{metric_col}") ~ age', data=data).fit()
                pvals[label] = ols_model.pvalues['age']

            # Build vertical text (stacked)
            text_lines = []
            for label in labels:
                p_value = pvals[label]
                significance = '*' if p_value < 0.05 else ''
                color = 'red' if p_value < 0.05 else 'black'
                text_lines.append(f"<span style='color:{color};'>p-{label} = {p_value:.3f}{significance}</span>")

            # Combine with HTML line breaks for vertical layout
            text_combined = "<br>".join(text_lines)

            # Add annotation box with all p-values
            fig.add_annotation(
            x=0.1,  
            y=1.0,  
            xref="x domain",
            yref="y domain",
            text=text_combined,
            align='left',  # align text within box
            showarrow=False,
            font=dict(size=12, family='Arial', color='black'),
            bgcolor='rgba(255,255,255,0.75)',
            bordercolor='black',
            borderwidth=1.5,
            borderpad=6,
            row=row_idx, col=1
        )


        # Axes
        fig.update_xaxes(
            title_text='Age',
            title_font=dict(size=18, family='Arial', color='black', weight='bold'),
            tickfont=dict(size=16, family='Arial', color='black'),
            tickvals=list(range(6, 18)),
            range=[5, 18],  
            row=row_idx, col=1
        )

        fig.update_yaxes(
            title_text=f'CSA in C{vert} (mm²)',
            title_font=dict(size=20, family='Arial', color='black', weight='bold'),
            tickfont=dict(size=16, family='Arial', color='black'),
            range=[0, 90],
            row=row_idx, col=1
        )

    # Layout
    fig.update_layout(
        height=2200,
        width=600,
        plot_bgcolor='white',
        paper_bgcolor='white',
        legend=dict(
            orientation="h",
            yanchor="bottom",
            y=1.02,
            xanchor="center",
            x=0.5,
            font=dict(size=14)
        )
    )

    fig.show()

In [25]:
df_GM_WM_SC

,Timestamp_WM,SCT Version_WM,Filename_WM,Slice (I->S)_WM,VertLevel_WM,DistancePMJ_WM,MEAN(area)_WM,STD(area)_WM,MEAN(angle_AP)_WM,STD(angle_AP)_WM,...,SUM(length)_SC,group_SC,scan_series_SC,height_SC,weight_SC,GM_WM_ratio,GM_SC_ratio,GM_percentage,WM_SC_ratio,WM_percentage
0,2025-12-10 18:45:24,7.1,/Users/samuellestonge/Documents/datasets/phila...,2:4,NaN,NaN,61.300003,4.364803,-0.350735,0.014703,...,15.008764,control,complete,NaN,NaN,0.275756,0.216149,21.614861,0.783840,78.384000
1,2025-12-10 18:45:26,7.1,/Users/samuellestonge/Documents/datasets/phila...,0:1,NaN,NaN,62.816458,0.877176,-0.476359,0.044769,...,10.010993,control,complete,NaN,NaN,0.253924,0.202449,20.244878,0.797282,79.728152
2,2025-12-10 18:45:28,7.1,/Users/samuellestonge/Documents/datasets/phila...,0:14,NaN,NaN,60.378424,2.527243,-0.788086,0.503706,...,75.129071,control,complete,NaN,NaN,0.245261,0.196949,19.694888,0.803016,80.301590
3,2025-12-10 18:45:22,7.1,/Users/samuellestonge/Documents/datasets/phila...,5:6,NaN,NaN,59.992678,0.503572,-0.397000,0.028898,...,10.001129,control,complete,NaN,NaN,0.275026,0.215705,21.570491,0.784307,78.430668
4,2025-12-10 18:45:20,7.1,/Users/samuellestonge/Documents/datasets/phila...,8,NaN,NaN,60.488738,0.000000,-0.629882,0.000000,...,5.001030,control,complete,NaN,NaN,0.272637,0.214219,21.421885,0.785730,78.573022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319,2025-12-10 18:45:50,7.1,/Users/samuellestonge/Documents/datasets/phila...,0:1,NaN,NaN,61.776319,2.105611,0.887651,0.136309,...,10.266154,control,complete,NaN,NaN,0.231947,0.188473,18.847260,0.812567,81.256681
320,2025-12-10 18:45:46,7.1,/Users/samuellestonge/Documents/datasets/phila...,5:6,NaN,NaN,55.147478,2.192907,1.410996,0.031612,...,10.018033,control,complete,NaN,NaN,0.214735,0.176743,17.674346,0.823077,82.307748
321,2025-12-10 18:45:48,7.1,/Users/samuellestonge/Documents/datasets/phila...,3:4,NaN,NaN,51.678180,0.801226,1.403146,0.035537,...,10.013795,control,complete,NaN,NaN,0.256263,0.204023,20.402309,0.796147,79.614669
322,2025-12-10 18:45:54,7.1,/Users/samuellestonge/Documents/datasets/phila...,0:14,NaN,NaN,55.052726,3.662056,0.909184,0.552296,...,65.590981,control,complete,NaN,NaN,0.241341,0.194472,19.447165,0.805795,80.579470
323,2025-12-10 18:45:45,7.1,/Users/samuellestonge/Documents/datasets/phila...,7:10,NaN,NaN,54.800750,1.303002,0.885455,0.297919,...,20.159814,control,complete,NaN,NaN,0.224153,0.183085,18.308500,0.816786,81.678592

In [ ]:
plot_CSA_all_labels(df_GM_WM_SC)

            Timestamp_WM  SCT Version_WM  \
5    2025-12-10 18:45:18             7.1
11   2025-12-10 18:44:20             7.1
12   2025-12-10 18:44:12             7.1
18   2025-12-10 18:44:57             7.1
24   2025-12-10 18:45:38             7.1
34   2025-12-10 18:44:48             7.1
41   2025-12-10 18:46:15             7.1
47   2025-12-10 18:44:55             7.1
53   2025-12-10 18:45:31             7.1
59   2025-12-10 18:45:46             7.1
60   2025-12-10 18:46:05             7.1
67   2025-12-10 18:46:00             7.1
72   2025-12-10 18:45:11             7.1
78   2025-12-10 18:44:26             7.1
84   2025-12-10 18:45:16             7.1
90   2025-12-10 18:45:23             7.1
96   2025-12-10 18:46:51             7.1
102  2025-12-10 18:46:13             7.1
113  2025-12-10 18:44:12             7.1
119  2025-12-10 18:46:15             7.1
125  2025-12-10 18:44:27             7.1
126  2025-12-10 18:44:12             7.1
132  2025-12-10 18:45:51             7.1
139  2025-12-10 18:45:28             7.1
149  2025-12-10 18:45:08             7.1
155  2025-12-10 18:44:39             7.1
161  2025-12-10 18:44:25             7.1
162  2025-12-10 18:46:35             7.1
172  2025-12-10 18:44:53             7.1
179  2025-12-10 18:46:34             7.1
180  2025-12-10 18:45:12             7.1
186  2025-12-10 18:44:25             7.1
192  2025-12-10 18:45:02             7.1
198  2025-12-10 18:46:29             7.1
209  2025-12-10 18:45:16             7.1
215  2025-12-10 18:44:25             7.1
216  2025-12-10 18:44:12             7.1
223  2025-12-10 18:44:58             7.1
233  2025-12-10 18:44:53             7.1
239  2025-12-10 18:46:51             7.1
245  2025-12-10 18:44:34             7.1
250  2025-12-10 18:46:14             7.1
252  2025-12-10 18:44:12             7.1
263  2025-12-10 18:46:00             7.1
269  2025-12-10 18:44:40             7.1
275  2025-12-10 18:44:25             7.1
276  2025-12-10 18:45:58             7.1
282  2025-12-10 18:44:43             7.1
292  2025-12-10 18:46:42             7.1
298  2025-12-10 18:45:40             7.1
301  2025-12-10 18:45:24             7.1
311  2025-12-10 18:45:01             7.1
317  2025-12-10 18:45:33             7.1
323  2025-12-10 18:45:45             7.1

                                           Filename_WM Slice (I->S)_WM  \
5    /Users/samuellestonge/Documents/datasets/phila...           10:11
11   /Users/samuellestonge/Documents/datasets/phila...           12:14
12   /Users/samuellestonge/Documents/datasets/phila...           11:14
18   /Users/samuellestonge/Documents/datasets/phila...           13:14
24   /Users/samuellestonge/Documents/datasets/phila...           10:13
34   /Users/samuellestonge/Documents/datasets/phila...           11:12
41   /Users/samuellestonge/Documents/datasets/phila...           13:14
47   /Users/samuellestonge/Documents/datasets/phila...            9:11
53   /Users/samuellestonge/Documents/datasets/phila...           11:13
59   /Users/samuellestonge/Documents/datasets/phila...            9:12
60   /Users/samuellestonge/Documents/datasets/phila...            9:11
67   /Users/samuellestonge/Documents/datasets/phila...           10:12
72   /Users/samuellestonge/Documents/datasets/phila...           10:12
78   /Users/samuellestonge/Documents/datasets/phila...           13:14
84   /Users/samuellestonge/Documents/datasets/phila...           13:14
90   /Users/samuellestonge/Documents/datasets/phila...           10:12
96   /Users/samuellestonge/Documents/datasets/phila...           11:12
102  /Users/samuellestonge/Documents/datasets/phila...           10:12
113  /Users/samuellestonge/Documents/datasets/phila...           13:14
119  /Users/samuellestonge/Documents/datasets/phila...            9:11
125  /Users/samuellestonge/Documents/datasets/phila...              14
126  /Users/samuellestonge/Documents/datasets/phila...            9:12
132  /Users/samuellestonge/Documents/datasets/phila...           11:14
139  /Users/samuellestonge/Documents/datasets/phila...           13:14
149  /Users/samuellestonge/Documents/datasets/phila...           12:14
155  /Users/samuellestonge/Documents/datasets/phila...              14
161  /Users/samuellestonge/Documents/datasets/phila...            0:14
162  /Users/samuellestonge/Documents/datasets/phila...           11:13
172  /Users/samuellestonge/Documents/datasets/phila...           11:13
179  /Users/samuellestonge/Documents/datasets/phila...           11:13
180  /Users/samuellestonge/Documents/datasets/phila...            9:11
186  /Users/samuellestonge/Documents/datasets/phila...            0:14
192  /Users/samuellestonge/Documents/datasets/phila...           12:14
198  /Users/samuellestonge/Documents/datasets/phila...           11:13
209  /Users/samuellestonge/Documents/datasets/phila...           10:13
215  /Users/samuellestonge/Documents/datasets/phila...           12:14
216  /Users/samuellestonge/Documents/datasets/phila...           12:13
223  /Users/samuellestonge/Documents/datasets/phila...           10:12
233  /Users/samuellestonge/Documents/datasets/phila...           10:11
239  /Users/samuellestonge/Documents/datasets/phila...           11:13
245  /Users/samuellestonge/Documents/datasets/phila...              14
250  /Users/samuellestonge/Documents/datasets/phila...           11:13
252  /Users/samuellestonge/Documents/datasets/phila...           11:12
263  /Users/samuellestonge/Documents/datasets/phila...           10:12
269  /Users/samuellestonge/Documents/datasets/phila...            0:14
275  /Users/samuellestonge/Documents/datasets/phila...           13:14
276  /Users/samuellestonge/Documents/datasets/phila...           10:12
282  /Users/samuellestonge/Documents/datasets/phila...           11:13
292  /Users/samuellestonge/Documents/datasets/phila...           10:12
298  /Users/samuellestonge/Documents/datasets/phila...           10:12
301  /Users/samuellestonge/Documents/datasets/phila...           11:12
311  /Users/samuellestonge/Documents/datasets/phila...           12:14
317  /Users/samuellestonge/Documents/datasets/phila...            8:11
323  /Users/samuellestonge/Documents/datasets/phila...            7:10

     VertLevel_WM  DistancePMJ_WM  MEAN(area)_WM  STD(area)_WM  \
5             NaN             NaN      59.272265      1.092535
11            NaN             NaN      54.537264      4.027795
12            NaN             NaN      51.048281      2.750562
18            NaN             NaN      63.254317      3.036252
24            NaN             NaN      70.706649      2.259067
34            NaN             NaN      54.275047      2.402596
41            NaN             NaN      66.536761      0.946572
47            NaN             NaN      51.264500      0.629723
53            NaN             NaN      56.839271      0.711170
59            NaN             NaN      60.236214      2.218529
60            NaN             NaN      64.445980      0.434808
67            NaN             NaN      58.983819      1.009486
72            NaN             NaN      58.888556      3.730589
78            NaN             NaN      67.168212      1.786731
84            NaN             NaN      60.845795      1.593231
90            NaN             NaN      53.417013      2.401862
96            NaN             NaN      45.548267      1.636631
102           NaN             NaN      52.932281      3.465203
113           NaN             NaN      63.468349      3.529683
119           NaN             NaN      50.792007      3.043348
125           NaN             NaN      51.474418      0.000000
126           NaN             NaN      59.800536      1.527132
132           NaN             NaN      59.657236      2.015422
139           NaN             NaN      59.412595      5.421551
149           NaN             NaN      63.946207      2.721436
155           NaN             NaN      63.156897      0.000000
161           NaN             NaN      56.340266      7.155077
162           NaN             NaN      52.116806      1.826223
172           NaN             NaN      69.928526      0.917708
179           NaN             NaN      47.973238      1.556550
180           NaN             NaN      57.385166      1.617348
186           NaN             NaN      60.021093      4.380368
192           NaN             NaN      46.920222      3.300633
198           NaN             NaN      63.675708      1.863705
209           NaN             NaN      51.200980      0.637662
215           NaN             NaN      67.952777      0.891664
216           NaN             NaN      46.087411      1.396457
223           NaN             NaN      62.352351      2.283374
233           NaN             NaN      46.880036      0.159986
239           NaN             NaN      67.812180      1.553480
245           NaN             NaN      61.327636      0.000000
250           NaN             NaN      65.585845      3.507489
252           NaN             NaN      73.135235      1.348926
263           NaN             NaN      52.389040      1.019975
269           NaN             NaN      52.805574      6.060704
275           NaN             NaN      46.825032      0.944857
276           NaN             NaN      50.057363      1.189254
282           NaN             NaN      61.456064     18.437219
292           NaN             NaN      62.492499      1.558456
298           NaN             NaN      57.854535      1.788361
301           NaN             NaN      59.624570      0.508737
311           NaN             NaN      56.526345      0.742415
317           NaN             NaN      51.122661      1.031887
323           NaN             NaN      54.800750      1.303002

     MEAN(angle_AP)_WM  STD(angle_AP)_WM  ...  MEAN(solidity)_SC  \
5            -1.054230          0.102535  ...           0.981364
11            3.277571          0.480251  ...           0.981699
12           -4.152304          0.787842  ...           0.978449
18           -1.037004          0.005484  ...           0.973642
24            2.001831          0.156633  ...           0.972910
34           -0.880766          0.131213  ...           0.981686
41            0.793774          0.328348  ...           0.985616
47            3.569730          0.230687  ...           0.979988
53           -0.700101          0.202561  ...           0.982367
59           -2.221376          0.137741  ...           0.982946
60           -2.801619          0.371616  ...           0.976763
67            3.031020          0.168556  ...           0.980390
72            0.808395          0.455089  ...           0.978596
78           -5.967371          0.020583  ...           0.980634
84           -4.563538          0.222569  ...           0.981032
90            4.377449          0.213141  ...           0.982421
96           -2.789894          0.328463  ...           0.980875
102           1.798691          0.263269  ...           0.975814
113           5.928131          0.484998  ...           0.977152
119           7.023733          0.136806  ...           0.984484
125          -0.018462          0.000000  ...           0.971174
126          -3.708628          0.557376  ...           0.984976
132           0.409437          0.493192  ...           0.977824
139           2.332281          0.446899  ...           0.983148
149          -0.640219          0.214773  ...           0.979855
155          -0.453274          0.000000  ...           0.977353
161           2.935460          0.852752  ...           0.980689
162           2.822352          0.388830  ...           0.977931
172           1.083136          0.012993  ...           0.976307
179          -2.683876          0.193628  ...           0.984679
180           1.037908          0.334426  ...           0.980176
186          -3.953355          0.657945  ...           0.981569
192           2.912979          0.248162  ...           0.979365
198          -2.209079          0.220858  ...           0.988994
209           4.712790          0.590516  ...           0.985099
215           0.873930          0.148489  ...           0.981949
216           5.096764          0.215354  ...           0.975644
223           5.261720          0.111624  ...           0.978621
233          -4.638460          0.191245  ...           0.985756
239          -3.763786          0.282731  ...           0.982396
245           1.391080          0.000000  ...           0.978436
250           2.754048          0.084120  ...           0.987152
252          -3.402905          0.207241  ...           0.988252
263           0.318736          0.192731  ...           0.978587
269          -3.592064          0.828438  ...           0.982592
275          -0.310266          0.202260  ...           0.979634
276           4.421120          0.231758  ...           0.980451
282           0.374764          0.017773  ...           0.974843
292           0.750423          0.200089  ...           0.979660
298          -0.125454          0.103576  ...           0.972972
301           8.098540          0.120265  ...           0.979019
311          -0.194259          0.074184  ...           0.973431
317           2.711901          0.222513  ...           0.977988
323           0.885455          0.297919  ...           0.976301

     STD(solidity)_SC  SUM(length)_SC  group_SC  scan_series_SC  height_SC  \
5            0.000426       10.017366   control        complete        NaN
11           0.002213       15.206685   control        complete   1.676000
12           0.005650       20.148369   control        complete   1.651003
18           0.002815       10.180364   control        complete        NaN
24           0.006060       20.107083   control        complete        NaN
34           0.000803       10.206147   control        complete        NaN
41           0.004892       10.268295   control        complete        NaN
47           0.008410       15.043606   control        complete        NaN
53           0.002952       15.041463   control        complete        NaN
59           0.001601       20.046201   control        complete        NaN
60           0.000754       15.031268   control        complete        NaN
67           0.003347       15.024654   control        complete        NaN
72           0.004207       15.235600   control        complete        NaN
78           0.000211       10.113068   control        complete   1.524003
84           0.003680       10.042875   control        complete        NaN
90           0.003906       15.185355   control        complete        NaN
96           0.001972       10.152476   control        complete        NaN
102          0.005984       15.127320   control        complete        NaN
113          0.000991       10.247699   control        complete   1.778004
119          0.008936       15.249723   control        complete        NaN
125          0.000000        5.259583   control        complete   1.422403
126          0.001736       20.166607   control        complete   1.625603
132          0.005810       20.010441   control        complete        NaN
139          0.000788       10.167117   control        complete        NaN
149          0.001832       15.196815   control        complete        NaN
155          0.000000        5.008900   control        complete   1.778004
161          0.005707       75.786442   control        complete   1.753000
162          0.002060       15.302938   control        complete        NaN
172          0.002342       15.140797   control        complete        NaN
179          0.003696       15.174929   control        complete        NaN
180          0.005012       15.162533   control        complete        NaN
186          0.004611       75.326193   control        complete   1.676403
192          0.002295       15.051137   control        complete        NaN
198          0.002997       15.095269   control        complete        NaN
209          0.002028       20.188860   control        complete        NaN
215          0.001033       15.118720   control        complete   1.676403
216          0.001583       10.482598   control        complete   1.625603
223          0.004778       15.076577   control        complete        NaN
233          0.001515       10.050600   control        complete        NaN
239          0.002894       15.177142   control        complete        NaN
245          0.000000        5.139643   control        complete   1.498603
250          0.002515       15.272404   control        complete        NaN
252          0.000965       10.031763   control        complete   1.524000
263          0.001207       15.564102   control        complete        NaN
269          0.006273       75.371356   control        complete   1.524003
275          0.001420       10.130879   control        complete   1.574803
276          0.001922       15.107333   control        complete        NaN
282          0.004588       15.513675   control        complete        NaN
292          0.001704       15.022008   control        complete        NaN
298          0.002399       15.148168   control      incomplete        NaN
301          0.004954       10.169779   control        complete        NaN
311          0.004397       15.147575   control      incomplete        NaN
317          0.005161       20.124046   control        complete        NaN
323          0.003961       20.159814   control        complete        NaN

     weight_SC  GM_WM_ratio  GM_SC_ratio  WM_SC_ratio
5          NaN     0.210487     0.173882     0.826093
11   61.236000     0.216251     0.177873     0.822528
12   54.431091     0.223945     0.183026     0.817280
18         NaN     0.179903     0.152713     0.848863
24         NaN     0.189198     0.159127     0.841059
34         NaN     0.214568     0.176579     0.822950
41         NaN     0.197613     0.165015     0.835044
47         NaN     0.212444     0.175228     0.824820
53         NaN     0.201701     0.167830     0.832075
59         NaN     0.219400     0.179920     0.820054
60         NaN     0.232328     0.188530     0.811479
67         NaN     0.200386     0.166942     0.833104
72         NaN     0.239460     0.193200     0.806816
78   43.091281     0.201978     0.168100     0.832266
84         NaN     0.184272     0.155585     0.844320
90         NaN     0.200370     0.166931     0.833116
96         NaN     0.230689     0.187576     0.813116
102        NaN     0.223621     0.182752     0.817240
113  68.038864     0.203482     0.169214     0.831594
119        NaN     0.227873     0.185602     0.814498
125  31.751470     0.227692     0.185695     0.815556
126  52.163129     0.216083     0.177736     0.822532
132        NaN     0.197832     0.165151     0.834803
139        NaN     0.180843     0.152511     0.843332
149        NaN     0.189456     0.159249     0.840562
155  68.038864     0.185690     0.156647     0.843593
161  72.576000     0.263512     0.208621     0.791693
162        NaN     0.222835     0.182163     0.817478
172        NaN     0.206526     0.171141     0.828665
179        NaN     0.305525     0.234110     0.766255
180        NaN     0.259911     0.206326     0.793833
186  61.234978     0.267533     0.211055     0.788891
192        NaN     0.221159     0.181095     0.818843
198        NaN     0.205424     0.170415     0.829580
209        NaN     0.222483     0.181989     0.817989
215  72.574788     0.203444     0.169083     0.831101
216  52.163129     0.263324     0.208929     0.793430
223        NaN     0.214192     0.176429     0.823694
233        NaN     0.188411     0.158530     0.841406
239        NaN     0.215399     0.177062     0.822017
245  38.555356     0.210205     0.173922     0.827394
250        NaN     0.184252     0.155551     0.844228
252  35.381000     0.190766     0.160186     0.839696
263        NaN     0.226631     0.184606     0.814563
269  43.091281     0.253960     0.202521     0.797453
275  46.266428     0.205629     0.170409     0.828723
276        NaN     0.231706     0.188161     0.812069
282        NaN     0.180612     0.189118     1.047091

## Plot GM and WM percentages with respect to age

In [57]:
def plot_percentage(df, label, percent_min, percent_max):

    """
    This function plots the ratio between two metrics (e.g., GM and WM) across different spinal levels.

    Args:
        df (pd.DataFrame): DataFrame containing the data to plot. Must include columns 'age', 'sex', 'VertLevel', and the ratio column. 
        The ratio column should be named as '{label_1}_{label_2}_ratio'.
        label (str): The label we want to plot (in %) ('GM' or 'WM').
    """
    
    df = df.copy()

    # Vertebral levels to plot
    vert_levels = ['3', '4', '5', '6', '7', 'all_levels']

    # Define color of markers 
    color = "#222020"

    # Color for confidence interval
    ci_color = 'rgba(34, 32, 32, 0.35)' 

    fig = make_subplots(
        rows=6,
        cols=1,
        shared_xaxes=False,
        shared_yaxes=False,
        vertical_spacing=0.05,
        horizontal_spacing=0.1
    )

    for row_idx, vert in enumerate(vert_levels, start=1):

        # Filder data according to the VertLevel
        data = df[df['Spinal_Level'] == vert].copy()

        print(data)

        x_range = np.linspace(data['age'].min(), data['age'].max(), 100)
        pred_df = pd.DataFrame({'age': x_range})

        ratio_name = f'{label}_percentage'
        ols_formula = f'{ratio_name} ~ age'

        ols_model = smf.ols(formula=ols_formula, data=data)
        ols_results = ols_model.fit()

        # Print OLS results
        print(ols_results.summary())

        pred = ols_results.get_prediction(pred_df)
        pred_summary = pred.summary_frame(alpha=0.05)

        y_fit = pred_summary['mean']
        ci_lower = pred_summary['mean_ci_lower']
        ci_upper = pred_summary['mean_ci_upper']

        # Scatter plot
        fig.add_trace(
            go.Scatter(
                x=data['age'],
                y=data[ratio_name],
                mode='markers',
                marker=dict(color=color, size=11, symbol='circle', opacity=0.8),
                showlegend=False
            ),
            row=row_idx, col=1
        )

        # Fit line
        fig.add_trace(
            go.Scatter(
                x=x_range,
                y=y_fit,
                mode='lines',
                line=dict(color=color, width=2, dash='solid'),
                showlegend=False
            ),
            row=row_idx, col=1
        )

        # Confidence interval
        fig.add_trace(
            go.Scatter(
                x=np.concatenate([x_range, x_range[::-1]]),
                y=np.concatenate([ci_upper, ci_lower[::-1]]),
                fill='toself',
                fillcolor=ci_color,
                line=dict(color='rgba(255,255,255,0)'),
                hoverinfo='skip',
                showlegend=False,
            ),
            row=row_idx, col=1
        )

        # Add p-value as annotation
        p_value = ols_results.pvalues['age']
        significance = ''
        if p_value < 0.05:
            significance = '*'
            font_color='red'
        else:
            font_color='black'
            
        fig.add_annotation(
            x=0.88,  # relative within subplot (0–1)
            y=0.98,  # near the top
            xref="x domain",
            yref="y domain",
            text = f'p-Age = {p_value:.3f} <span style="color:{font_color}">{significance}</span>',
            showarrow=False,
            font=dict(family='Arial', size=16, color='black'),
            bgcolor='rgba(255, 255, 255, 0.7)',
            bordercolor='black',
            borderwidth=1,
            borderpad=4,
            row=row_idx, col=1
        )

        fig.update_xaxes(
                title_text='Age',
                title_font=dict(family='Arial', size=20, color='black', weight='bold'),
                tickfont=dict(family='Arial', size=18),
                tickvals=list(range(6, 18)),
                range=[5, 18],
                row=row_idx, col=1
            )
        
        fig.update_yaxes(
                title_text=f'% {label} in C{vert}',
                title_font=dict(family='Arial', size=20, color='black', weight='bold'),
                tickfont=dict(family='Arial', size=18),
                range=[percent_min, percent_max],
                row=row_idx, col=1
            )

    # Update layout
    fig.update_layout(
        height=1800,
        width=600,
        plot_bgcolor="#ffffff",
        paper_bgcolor="#ffffff"
    )

    fig.show()

## Plot GM% vs Age

In [58]:
plot_percentage(df_GM_WM_SC, 'GM', 15, 25)

            Timestamp_WM  SCT Version_WM  \
5    2025-12-10 18:45:18             7.1
11   2025-12-10 18:44:20             7.1
12   2025-12-10 18:44:12             7.1
18   2025-12-10 18:44:57             7.1
24   2025-12-10 18:45:38             7.1
34   2025-12-10 18:44:48             7.1
41   2025-12-10 18:46:15             7.1
47   2025-12-10 18:44:55             7.1
53   2025-12-10 18:45:31             7.1
59   2025-12-10 18:45:46             7.1
60   2025-12-10 18:46:05             7.1
67   2025-12-10 18:46:00             7.1
72   2025-12-10 18:45:11             7.1
78   2025-12-10 18:44:26             7.1
84   2025-12-10 18:45:16             7.1
90   2025-12-10 18:45:23             7.1
96   2025-12-10 18:46:51             7.1
102  2025-12-10 18:46:13             7.1
113  2025-12-10 18:44:12             7.1
119  2025-12-10 18:46:15             7.1
125  2025-12-10 18:44:27             7.1
126  2025-12-10 18:44:12             7.1
132  2025-12-10 18:45:51             7.1
139  2025-12-10 18:45:28             7.1
149  2025-12-10 18:45:08             7.1
155  2025-12-10 18:44:39             7.1
161  2025-12-10 18:44:25             7.1
162  2025-12-10 18:46:35             7.1
172  2025-12-10 18:44:53             7.1
179  2025-12-10 18:46:34             7.1
180  2025-12-10 18:45:12             7.1
186  2025-12-10 18:44:25             7.1
192  2025-12-10 18:45:02             7.1
198  2025-12-10 18:46:29             7.1
209  2025-12-10 18:45:16             7.1
215  2025-12-10 18:44:25             7.1
216  2025-12-10 18:44:12             7.1
223  2025-12-10 18:44:58             7.1
233  2025-12-10 18:44:53             7.1
239  2025-12-10 18:46:51             7.1
245  2025-12-10 18:44:34             7.1
250  2025-12-10 18:46:14             7.1
252  2025-12-10 18:44:12             7.1
263  2025-12-10 18:46:00             7.1
269  2025-12-10 18:44:40             7.1
275  2025-12-10 18:44:25             7.1
276  2025-12-10 18:45:58             7.1
282  2025-12-10 18:44:43             7.1
292  2025-12-10 18:46:42             7.1
298  2025-12-10 18:45:40             7.1
301  2025-12-10 18:45:24             7.1
311  2025-12-10 18:45:01             7.1
317  2025-12-10 18:45:33             7.1
323  2025-12-10 18:45:45             7.1

                                           Filename_WM Slice (I->S)_WM  \
5    /Users/samuellestonge/Documents/datasets/phila...           10:11
11   /Users/samuellestonge/Documents/datasets/phila...           12:14
12   /Users/samuellestonge/Documents/datasets/phila...           11:14
18   /Users/samuellestonge/Documents/datasets/phila...           13:14
24   /Users/samuellestonge/Documents/datasets/phila...           10:13
34   /Users/samuellestonge/Documents/datasets/phila...           11:12
41   /Users/samuellestonge/Documents/datasets/phila...           13:14
47   /Users/samuellestonge/Documents/datasets/phila...            9:11
53   /Users/samuellestonge/Documents/datasets/phila...           11:13
59   /Users/samuellestonge/Documents/datasets/phila...            9:12
60   /Users/samuellestonge/Documents/datasets/phila...            9:11
67   /Users/samuellestonge/Documents/datasets/phila...           10:12
72   /Users/samuellestonge/Documents/datasets/phila...           10:12
78   /Users/samuellestonge/Documents/datasets/phila...           13:14
84   /Users/samuellestonge/Documents/datasets/phila...           13:14
90   /Users/samuellestonge/Documents/datasets/phila...           10:12
96   /Users/samuellestonge/Documents/datasets/phila...           11:12
102  /Users/samuellestonge/Documents/datasets/phila...           10:12
113  /Users/samuellestonge/Documents/datasets/phila...           13:14
119  /Users/samuellestonge/Documents/datasets/phila...            9:11
125  /Users/samuellestonge/Documents/datasets/phila...              14
126  /Users/samuellestonge/Documents/datasets/phila...            9:12
132  /Users/samuellestonge/Documents/datasets/phila...           11:14
139  /Users/samuellestonge/Documents/datasets/phila...           13:14
149  /Users/samuellestonge/Documents/datasets/phila...           12:14
155  /Users/samuellestonge/Documents/datasets/phila...              14
161  /Users/samuellestonge/Documents/datasets/phila...            0:14
162  /Users/samuellestonge/Documents/datasets/phila...           11:13
172  /Users/samuellestonge/Documents/datasets/phila...           11:13
179  /Users/samuellestonge/Documents/datasets/phila...           11:13
180  /Users/samuellestonge/Documents/datasets/phila...            9:11
186  /Users/samuellestonge/Documents/datasets/phila...            0:14
192  /Users/samuellestonge/Documents/datasets/phila...           12:14
198  /Users/samuellestonge/Documents/datasets/phila...           11:13
209  /Users/samuellestonge/Documents/datasets/phila...           10:13
215  /Users/samuellestonge/Documents/datasets/phila...           12:14
216  /Users/samuellestonge/Documents/datasets/phila...           12:13
223  /Users/samuellestonge/Documents/datasets/phila...           10:12
233  /Users/samuellestonge/Documents/datasets/phila...           10:11
239  /Users/samuellestonge/Documents/datasets/phila...           11:13
245  /Users/samuellestonge/Documents/datasets/phila...              14
250  /Users/samuellestonge/Documents/datasets/phila...           11:13
252  /Users/samuellestonge/Documents/datasets/phila...           11:12
263  /Users/samuellestonge/Documents/datasets/phila...           10:12
269  /Users/samuellestonge/Documents/datasets/phila...            0:14
275  /Users/samuellestonge/Documents/datasets/phila...           13:14
276  /Users/samuellestonge/Documents/datasets/phila...           10:12
282  /Users/samuellestonge/Documents/datasets/phila...           11:13
292  /Users/samuellestonge/Documents/datasets/phila...           10:12
298  /Users/samuellestonge/Documents/datasets/phila...           10:12
301  /Users/samuellestonge/Documents/datasets/phila...           11:12
311  /Users/samuellestonge/Documents/datasets/phila...           12:14
317  /Users/samuellestonge/Documents/datasets/phila...            8:11
323  /Users/samuellestonge/Documents/datasets/phila...            7:10

     VertLevel_WM  DistancePMJ_WM  MEAN(area)_WM  STD(area)_WM  \
5             NaN             NaN      59.272265      1.092535
11            NaN             NaN      54.537264      4.027795
12            NaN             NaN      51.048281      2.750562
18            NaN             NaN      63.254317      3.036252
24            NaN             NaN      70.706649      2.259067
34            NaN             NaN      54.275047      2.402596
41            NaN             NaN      66.536761      0.946572
47            NaN             NaN      51.264500      0.629723
53            NaN             NaN      56.839271      0.711170
59            NaN             NaN      60.236214      2.218529
60            NaN             NaN      64.445980      0.434808
67            NaN             NaN      58.983819      1.009486
72            NaN             NaN      58.888556      3.730589
78            NaN             NaN      67.168212      1.786731
84            NaN             NaN      60.845795      1.593231
90            NaN             NaN      53.417013      2.401862
96            NaN             NaN      45.548267      1.636631
102           NaN             NaN      52.932281      3.465203
113           NaN             NaN      63.468349      3.529683
119           NaN             NaN      50.792007      3.043348
125           NaN             NaN      51.474418      0.000000
126           NaN             NaN      59.800536      1.527132
132           NaN             NaN      59.657236      2.015422
139           NaN             NaN      59.412595      5.421551
149           NaN             NaN      63.946207      2.721436
155           NaN             NaN      63.156897      0.000000
161           NaN             NaN      56.340266      7.155077
162           NaN             NaN      52.116806      1.826223
172           NaN             NaN      69.928526      0.917708
179           NaN             NaN      47.973238      1.556550
180           NaN             NaN      57.385166      1.617348
186           NaN             NaN      60.021093      4.380368
192           NaN             NaN      46.920222      3.300633
198           NaN             NaN      63.675708      1.863705
209           NaN             NaN      51.200980      0.637662
215           NaN             NaN      67.952777      0.891664
216           NaN             NaN      46.087411      1.396457
223           NaN             NaN      62.352351      2.283374
233           NaN             NaN      46.880036      0.159986
239           NaN             NaN      67.812180      1.553480
245           NaN             NaN      61.327636      0.000000
250           NaN             NaN      65.585845      3.507489
252           NaN             NaN      73.135235      1.348926
263           NaN             NaN      52.389040      1.019975
269           NaN             NaN      52.805574      6.060704
275           NaN             NaN      46.825032      0.944857
276           NaN             NaN      50.057363      1.189254
282           NaN             NaN      61.456064     18.437219
292           NaN             NaN      62.492499      1.558456
298           NaN             NaN      57.854535      1.788361
301           NaN             NaN      59.624570      0.508737
311           NaN             NaN      56.526345      0.742415
317           NaN             NaN      51.122661      1.031887
323           NaN             NaN      54.800750      1.303002

     MEAN(angle_AP)_WM  STD(angle_AP)_WM  ...  SUM(length)_SC  group_SC  \
5            -1.054230          0.102535  ...       10.017366   control
11            3.277571          0.480251  ...       15.206685   control
12           -4.152304          0.787842  ...       20.148369   control
18           -1.037004          0.005484  ...       10.180364   control
24            2.001831          0.156633  ...       20.107083   control
34           -0.880766          0.131213  ...       10.206147   control
41            0.793774          0.328348  ...       10.268295   control
47            3.569730          0.230687  ...       15.043606   control
53           -0.700101          0.202561  ...       15.041463   control
59           -2.221376          0.137741  ...       20.046201   control
60           -2.801619          0.371616  ...       15.031268   control
67            3.031020          0.168556  ...       15.024654   control
72            0.808395          0.455089  ...       15.235600   control
78           -5.967371          0.020583  ...       10.113068   control
84           -4.563538          0.222569  ...       10.042875   control
90            4.377449          0.213141  ...       15.185355   control
96           -2.789894          0.328463  ...       10.152476   control
102           1.798691          0.263269  ...       15.127320   control
113           5.928131          0.484998  ...       10.247699   control
119           7.023733          0.136806  ...       15.249723   control
125          -0.018462          0.000000  ...        5.259583   control
126          -3.708628          0.557376  ...       20.166607   control
132           0.409437          0.493192  ...       20.010441   control
139           2.332281          0.446899  ...       10.167117   control
149          -0.640219          0.214773  ...       15.196815   control
155          -0.453274          0.000000  ...        5.008900   control
161           2.935460          0.852752  ...       75.786442   control
162           2.822352          0.388830  ...       15.302938   control
172           1.083136          0.012993  ...       15.140797   control
179          -2.683876          0.193628  ...       15.174929   control
180           1.037908          0.334426  ...       15.162533   control
186          -3.953355          0.657945  ...       75.326193   control
192           2.912979          0.248162  ...       15.051137   control
198          -2.209079          0.220858  ...       15.095269   control
209           4.712790          0.590516  ...       20.188860   control
215           0.873930          0.148489  ...       15.118720   control
216           5.096764          0.215354  ...       10.482598   control
223           5.261720          0.111624  ...       15.076577   control
233          -4.638460          0.191245  ...       10.050600   control
239          -3.763786          0.282731  ...       15.177142   control
245           1.391080          0.000000  ...        5.139643   control
250           2.754048          0.084120  ...       15.272404   control
252          -3.402905          0.207241  ...       10.031763   control
263           0.318736          0.192731  ...       15.564102   control
269          -3.592064          0.828438  ...       75.371356   control
275          -0.310266          0.202260  ...       10.130879   control
276           4.421120          0.231758  ...       15.107333   control
282           0.374764          0.017773  ...       15.513675   control
292           0.750423          0.200089  ...       15.022008   control
298          -0.125454          0.103576  ...       15.148168   control
301           8.098540          0.120265  ...       10.169779   control
311          -0.194259          0.074184  ...       15.147575   control
317           2.711901          0.222513  ...       20.124046   control
323           0.885455          0.297919  ...       20.159814   control

     scan_series_SC  height_SC  weight_SC  GM_WM_ratio  GM_SC_ratio  \
5          complete        NaN        NaN     0.210487     0.173882
11         complete   1.676000  61.236000     0.216251     0.177873
12         complete   1.651003  54.431091     0.223945     0.183026
18         complete        NaN        NaN     0.179903     0.152713
24         complete        NaN        NaN     0.189198     0.159127
34         complete        NaN        NaN     0.214568     0.176579
41         complete        NaN        NaN     0.197613     0.165015
47         complete        NaN        NaN     0.212444     0.175228
53         complete        NaN        NaN     0.201701     0.167830
59         complete        NaN        NaN     0.219400     0.179920
60         complete        NaN        NaN     0.232328     0.188530
67         complete        NaN        NaN     0.200386     0.166942
72         complete        NaN        NaN     0.239460     0.193200
78         complete   1.524003  43.091281     0.201978     0.168100
84         complete        NaN        NaN     0.184272     0.155585
90         complete        NaN        NaN     0.200370     0.166931
96         complete        NaN        NaN     0.230689     0.187576
102        complete        NaN        NaN     0.223621     0.182752
113        complete   1.778004  68.038864     0.203482     0.169214
119        complete        NaN        NaN     0.227873     0.185602
125        complete   1.422403  31.751470     0.227692     0.185695
126        complete   1.625603  52.163129     0.216083     0.177736
132        complete        NaN        NaN     0.197832     0.165151
139        complete        NaN        NaN     0.180843     0.152511
149        complete        NaN        NaN     0.189456     0.159249
155        complete   1.778004  68.038864     0.185690     0.156647
161        complete   1.753000  72.576000     0.263512     0.208621
162        complete        NaN        NaN     0.222835     0.182163
172        complete        NaN        NaN     0.206526     0.171141
179        complete        NaN        NaN     0.305525     0.234110
180        complete        NaN        NaN     0.259911     0.206326
186        complete   1.676403  61.234978     0.267533     0.211055
192        complete        NaN        NaN     0.221159     0.181095
198        complete        NaN        NaN     0.205424     0.170415
209        complete        NaN        NaN     0.222483     0.181989
215        complete   1.676403  72.574788     0.203444     0.169083
216        complete   1.625603  52.163129     0.263324     0.208929
223        complete        NaN        NaN     0.214192     0.176429
233        complete        NaN        NaN     0.188411     0.158530
239        complete        NaN        NaN     0.215399     0.177062
245        complete   1.498603  38.555356     0.210205     0.173922
250        complete        NaN        NaN     0.184252     0.155551
252        complete   1.524000  35.381000     0.190766     0.160186
263        complete        NaN        NaN     0.226631     0.184606
269        complete   1.524003  43.091281     0.253960     0.202521
275        complete   1.574803  46.266428     0.205629     0.170409
276        complete        NaN        NaN     0.231706     0.188161
282        complete        NaN        NaN     0.180612     0.189118
292        complete        NaN        NaN     0.224997     0.183669
298      incomplete        NaN        NaN     0.215225     0.177128
301        complete        NaN        NaN     0.201458     0.167609
311      incomplete        NaN        NaN     0.222472     0.182038
317        complete        NaN        NaN     0.208755     0.172682
323        complete        NaN        NaN     0.224153     0.183085

     GM_percentage  WM_SC_ratio  WM_percentage
5        17.388181     0.826093      82.609278
11       17.787274     0.822528      82.252798
12       18.302606     0.817280      81.727999
18       15.271336     0.848863      84.886347
24       15.912704     0.841059      84.105917
34       17.657868     0.822950      82.295022
41       16.501533     0.835044      83.504351
47       17.522789     0.824820      82.481958
53       16.783009     0.832075      83.207456
59       17.992000     0.820054      82.005419
60       18.852976     0.811479      81.147943
67       16.694230     0.833104      83.310447
72       19.320039     0.806816      80.681582
78       16.809975     0.832266      83.226630
84       15.558455     0.844320      84.431970
90       16.693116     0.833116      83.311571
96       18.757648     0.813116      81.311588
102      18.275225     0.817240      81.723980
113      16.921450     0.831594      83.159364
119      18.560212     0.814498      81.449796
125      18.569550     0.815556      81.555631
126      17.773552     0.822532      82.253237
132      16.515063     0.834803      83.480315
139      15.251074     0.843332      84.333192
149      15.924922     0.840562      84.056161
155      15.664656     0.843593      84.359349
161      20.862054     0.791693      79.169321
162      18.216295     0.817478      81.747843
172      17.114076     0.828665      82.866501
179      23.410987     0.766255      76.625528
180      20.632579     0.793833      79.383345
186      21.105457     0.788891      78.889129
192      18.109452     0.818843      81.884341
198      17.041539     0.829580      82.957990
209      18.198856     0.817989      81.798881
215      16.908279     0.831101      83.110150
216      20.892894     0.793430      79.342991
223      17.642878     0.823694      82.369389
233      15.852972     0.841406      84.140554
239      17.706184     0.822017      82.201730
245      17.392196     0.827394      82.739370
250      15.555062     0.844228      84.422823
252      16.018560     0.839696      83.969573
263      18.460565     0.814563      81.456316
269      20.252143     0.797453      79.745301
275      17.040928     0.828723      82.872290
276      18.816111     0.812069      81.206935
282      18.911757     1.047091     104.709129
292      18.366900     0.816317      81.631672
298      17.712811     0.822989      82.298913
301      16.760895     0.831980      83.197954
311      18.203796     0.818250      81.824954
317      17.268172     0.827199      82.719878
323      18.308500     0.816786      81.678592

[54 rows x 90 columns]

## Plot WM% vs Age

In [41]:
plot_percentage(df_GM_WM_SC, 'WM', 70, 90)

            Timestamp_WM  SCT Version_WM  \
5    2025-12-10 18:45:18             7.1
11   2025-12-10 18:44:20             7.1
12   2025-12-10 18:44:12             7.1
18   2025-12-10 18:44:57             7.1
24   2025-12-10 18:45:38             7.1
34   2025-12-10 18:44:48             7.1
41   2025-12-10 18:46:15             7.1
47   2025-12-10 18:44:55             7.1
53   2025-12-10 18:45:31             7.1
59   2025-12-10 18:45:46             7.1
60   2025-12-10 18:46:05             7.1
67   2025-12-10 18:46:00             7.1
72   2025-12-10 18:45:11             7.1
78   2025-12-10 18:44:26             7.1
84   2025-12-10 18:45:16             7.1
90   2025-12-10 18:45:23             7.1
96   2025-12-10 18:46:51             7.1
102  2025-12-10 18:46:13             7.1
113  2025-12-10 18:44:12             7.1
119  2025-12-10 18:46:15             7.1
125  2025-12-10 18:44:27             7.1
126  2025-12-10 18:44:12             7.1
132  2025-12-10 18:45:51             7.1
139  2025-12-10 18:45:28             7.1
149  2025-12-10 18:45:08             7.1
155  2025-12-10 18:44:39             7.1
161  2025-12-10 18:44:25             7.1
162  2025-12-10 18:46:35             7.1
172  2025-12-10 18:44:53             7.1
179  2025-12-10 18:46:34             7.1
180  2025-12-10 18:45:12             7.1
186  2025-12-10 18:44:25             7.1
192  2025-12-10 18:45:02             7.1
198  2025-12-10 18:46:29             7.1
209  2025-12-10 18:45:16             7.1
215  2025-12-10 18:44:25             7.1
216  2025-12-10 18:44:12             7.1
223  2025-12-10 18:44:58             7.1
233  2025-12-10 18:44:53             7.1
239  2025-12-10 18:46:51             7.1
245  2025-12-10 18:44:34             7.1
250  2025-12-10 18:46:14             7.1
252  2025-12-10 18:44:12             7.1
263  2025-12-10 18:46:00             7.1
269  2025-12-10 18:44:40             7.1
275  2025-12-10 18:44:25             7.1
276  2025-12-10 18:45:58             7.1
282  2025-12-10 18:44:43             7.1
292  2025-12-10 18:46:42             7.1
298  2025-12-10 18:45:40             7.1
301  2025-12-10 18:45:24             7.1
311  2025-12-10 18:45:01             7.1
317  2025-12-10 18:45:33             7.1
323  2025-12-10 18:45:45             7.1

                                           Filename_WM Slice (I->S)_WM  \
5    /Users/samuellestonge/Documents/datasets/phila...           10:11
11   /Users/samuellestonge/Documents/datasets/phila...           12:14
12   /Users/samuellestonge/Documents/datasets/phila...           11:14
18   /Users/samuellestonge/Documents/datasets/phila...           13:14
24   /Users/samuellestonge/Documents/datasets/phila...           10:13
34   /Users/samuellestonge/Documents/datasets/phila...           11:12
41   /Users/samuellestonge/Documents/datasets/phila...           13:14
47   /Users/samuellestonge/Documents/datasets/phila...            9:11
53   /Users/samuellestonge/Documents/datasets/phila...           11:13
59   /Users/samuellestonge/Documents/datasets/phila...            9:12
60   /Users/samuellestonge/Documents/datasets/phila...            9:11
67   /Users/samuellestonge/Documents/datasets/phila...           10:12
72   /Users/samuellestonge/Documents/datasets/phila...           10:12
78   /Users/samuellestonge/Documents/datasets/phila...           13:14
84   /Users/samuellestonge/Documents/datasets/phila...           13:14
90   /Users/samuellestonge/Documents/datasets/phila...           10:12
96   /Users/samuellestonge/Documents/datasets/phila...           11:12
102  /Users/samuellestonge/Documents/datasets/phila...           10:12
113  /Users/samuellestonge/Documents/datasets/phila...           13:14
119  /Users/samuellestonge/Documents/datasets/phila...            9:11
125  /Users/samuellestonge/Documents/datasets/phila...              14
126  /Users/samuellestonge/Documents/datasets/phila...            9:12
132  /Users/samuellestonge/Documents/datasets/phila...           11:14
139  /Users/samuellestonge/Documents/datasets/phila...           13:14
149  /Users/samuellestonge/Documents/datasets/phila...           12:14
155  /Users/samuellestonge/Documents/datasets/phila...              14
161  /Users/samuellestonge/Documents/datasets/phila...            0:14
162  /Users/samuellestonge/Documents/datasets/phila...           11:13
172  /Users/samuellestonge/Documents/datasets/phila...           11:13
179  /Users/samuellestonge/Documents/datasets/phila...           11:13
180  /Users/samuellestonge/Documents/datasets/phila...            9:11
186  /Users/samuellestonge/Documents/datasets/phila...            0:14
192  /Users/samuellestonge/Documents/datasets/phila...           12:14
198  /Users/samuellestonge/Documents/datasets/phila...           11:13
209  /Users/samuellestonge/Documents/datasets/phila...           10:13
215  /Users/samuellestonge/Documents/datasets/phila...           12:14
216  /Users/samuellestonge/Documents/datasets/phila...           12:13
223  /Users/samuellestonge/Documents/datasets/phila...           10:12
233  /Users/samuellestonge/Documents/datasets/phila...           10:11
239  /Users/samuellestonge/Documents/datasets/phila...           11:13
245  /Users/samuellestonge/Documents/datasets/phila...              14
250  /Users/samuellestonge/Documents/datasets/phila...           11:13
252  /Users/samuellestonge/Documents/datasets/phila...           11:12
263  /Users/samuellestonge/Documents/datasets/phila...           10:12
269  /Users/samuellestonge/Documents/datasets/phila...            0:14
275  /Users/samuellestonge/Documents/datasets/phila...           13:14
276  /Users/samuellestonge/Documents/datasets/phila...           10:12
282  /Users/samuellestonge/Documents/datasets/phila...           11:13
292  /Users/samuellestonge/Documents/datasets/phila...           10:12
298  /Users/samuellestonge/Documents/datasets/phila...           10:12
301  /Users/samuellestonge/Documents/datasets/phila...           11:12
311  /Users/samuellestonge/Documents/datasets/phila...           12:14
317  /Users/samuellestonge/Documents/datasets/phila...            8:11
323  /Users/samuellestonge/Documents/datasets/phila...            7:10

     VertLevel_WM  DistancePMJ_WM  MEAN(area)_WM  STD(area)_WM  \
5             NaN             NaN      59.272265      1.092535
11            NaN             NaN      54.537264      4.027795
12            NaN             NaN      51.048281      2.750562
18            NaN             NaN      63.254317      3.036252
24            NaN             NaN      70.706649      2.259067
34            NaN             NaN      54.275047      2.402596
41            NaN             NaN      66.536761      0.946572
47            NaN             NaN      51.264500      0.629723
53            NaN             NaN      56.839271      0.711170
59            NaN             NaN      60.236214      2.218529
60            NaN             NaN      64.445980      0.434808
67            NaN             NaN      58.983819      1.009486
72            NaN             NaN      58.888556      3.730589
78            NaN             NaN      67.168212      1.786731
84            NaN             NaN      60.845795      1.593231
90            NaN             NaN      53.417013      2.401862
96            NaN             NaN      45.548267      1.636631
102           NaN             NaN      52.932281      3.465203
113           NaN             NaN      63.468349      3.529683
119           NaN             NaN      50.792007      3.043348
125           NaN             NaN      51.474418      0.000000
126           NaN             NaN      59.800536      1.527132
132           NaN             NaN      59.657236      2.015422
139           NaN             NaN      59.412595      5.421551
149           NaN             NaN      63.946207      2.721436
155           NaN             NaN      63.156897      0.000000
161           NaN             NaN      56.340266      7.155077
162           NaN             NaN      52.116806      1.826223
172           NaN             NaN      69.928526      0.917708
179           NaN             NaN      47.973238      1.556550
180           NaN             NaN      57.385166      1.617348
186           NaN             NaN      60.021093      4.380368
192           NaN             NaN      46.920222      3.300633
198           NaN             NaN      63.675708      1.863705
209           NaN             NaN      51.200980      0.637662
215           NaN             NaN      67.952777      0.891664
216           NaN             NaN      46.087411      1.396457
223           NaN             NaN      62.352351      2.283374
233           NaN             NaN      46.880036      0.159986
239           NaN             NaN      67.812180      1.553480
245           NaN             NaN      61.327636      0.000000
250           NaN             NaN      65.585845      3.507489
252           NaN             NaN      73.135235      1.348926
263           NaN             NaN      52.389040      1.019975
269           NaN             NaN      52.805574      6.060704
275           NaN             NaN      46.825032      0.944857
276           NaN             NaN      50.057363      1.189254
282           NaN             NaN      61.456064     18.437219
292           NaN             NaN      62.492499      1.558456
298           NaN             NaN      57.854535      1.788361
301           NaN             NaN      59.624570      0.508737
311           NaN             NaN      56.526345      0.742415
317           NaN             NaN      51.122661      1.031887
323           NaN             NaN      54.800750      1.303002

     MEAN(angle_AP)_WM  STD(angle_AP)_WM  ...  SUM(length)_SC  group_SC  \
5            -1.054230          0.102535  ...       10.017366   control
11            3.277571          0.480251  ...       15.206685   control
12           -4.152304          0.787842  ...       20.148369   control
18           -1.037004          0.005484  ...       10.180364   control
24            2.001831          0.156633  ...       20.107083   control
34           -0.880766          0.131213  ...       10.206147   control
41            0.793774          0.328348  ...       10.268295   control
47            3.569730          0.230687  ...       15.043606   control
53           -0.700101          0.202561  ...       15.041463   control
59           -2.221376          0.137741  ...       20.046201   control
60           -2.801619          0.371616  ...       15.031268   control
67            3.031020          0.168556  ...       15.024654   control
72            0.808395          0.455089  ...       15.235600   control
78           -5.967371          0.020583  ...       10.113068   control
84           -4.563538          0.222569  ...       10.042875   control
90            4.377449          0.213141  ...       15.185355   control
96           -2.789894          0.328463  ...       10.152476   control
102           1.798691          0.263269  ...       15.127320   control
113           5.928131          0.484998  ...       10.247699   control
119           7.023733          0.136806  ...       15.249723   control
125          -0.018462          0.000000  ...        5.259583   control
126          -3.708628          0.557376  ...       20.166607   control
132           0.409437          0.493192  ...       20.010441   control
139           2.332281          0.446899  ...       10.167117   control
149          -0.640219          0.214773  ...       15.196815   control
155          -0.453274          0.000000  ...        5.008900   control
161           2.935460          0.852752  ...       75.786442   control
162           2.822352          0.388830  ...       15.302938   control
172           1.083136          0.012993  ...       15.140797   control
179          -2.683876          0.193628  ...       15.174929   control
180           1.037908          0.334426  ...       15.162533   control
186          -3.953355          0.657945  ...       75.326193   control
192           2.912979          0.248162  ...       15.051137   control
198          -2.209079          0.220858  ...       15.095269   control
209           4.712790          0.590516  ...       20.188860   control
215           0.873930          0.148489  ...       15.118720   control
216           5.096764          0.215354  ...       10.482598   control
223           5.261720          0.111624  ...       15.076577   control
233          -4.638460          0.191245  ...       10.050600   control
239          -3.763786          0.282731  ...       15.177142   control
245           1.391080          0.000000  ...        5.139643   control
250           2.754048          0.084120  ...       15.272404   control
252          -3.402905          0.207241  ...       10.031763   control
263           0.318736          0.192731  ...       15.564102   control
269          -3.592064          0.828438  ...       75.371356   control
275          -0.310266          0.202260  ...       10.130879   control
276           4.421120          0.231758  ...       15.107333   control
282           0.374764          0.017773  ...       15.513675   control
292           0.750423          0.200089  ...       15.022008   control
298          -0.125454          0.103576  ...       15.148168   control
301           8.098540          0.120265  ...       10.169779   control
311          -0.194259          0.074184  ...       15.147575   control
317           2.711901          0.222513  ...       20.124046   control
323           0.885455          0.297919  ...       20.159814   control

     scan_series_SC  height_SC  weight_SC  GM_WM_ratio  GM_SC_ratio  \
5          complete        NaN        NaN     0.210487     0.173882
11         complete   1.676000  61.236000     0.216251     0.177873
12         complete   1.651003  54.431091     0.223945     0.183026
18         complete        NaN        NaN     0.179903     0.152713
24         complete        NaN        NaN     0.189198     0.159127
34         complete        NaN        NaN     0.214568     0.176579
41         complete        NaN        NaN     0.197613     0.165015
47         complete        NaN        NaN     0.212444     0.175228
53         complete        NaN        NaN     0.201701     0.167830
59         complete        NaN        NaN     0.219400     0.179920
60         complete        NaN        NaN     0.232328     0.188530
67         complete        NaN        NaN     0.200386     0.166942
72         complete        NaN        NaN     0.239460     0.193200
78         complete   1.524003  43.091281     0.201978     0.168100
84         complete        NaN        NaN     0.184272     0.155585
90         complete        NaN        NaN     0.200370     0.166931
96         complete        NaN        NaN     0.230689     0.187576
102        complete        NaN        NaN     0.223621     0.182752
113        complete   1.778004  68.038864     0.203482     0.169214
119        complete        NaN        NaN     0.227873     0.185602
125        complete   1.422403  31.751470     0.227692     0.185695
126        complete   1.625603  52.163129     0.216083     0.177736
132        complete        NaN        NaN     0.197832     0.165151
139        complete        NaN        NaN     0.180843     0.152511
149        complete        NaN        NaN     0.189456     0.159249
155        complete   1.778004  68.038864     0.185690     0.156647
161        complete   1.753000  72.576000     0.263512     0.208621
162        complete        NaN        NaN     0.222835     0.182163
172        complete        NaN        NaN     0.206526     0.171141
179        complete        NaN        NaN     0.305525     0.234110
180        complete        NaN        NaN     0.259911     0.206326
186        complete   1.676403  61.234978     0.267533     0.211055
192        complete        NaN        NaN     0.221159     0.181095
198        complete        NaN        NaN     0.205424     0.170415
209        complete        NaN        NaN     0.222483     0.181989
215        complete   1.676403  72.574788     0.203444     0.169083
216        complete   1.625603  52.163129     0.263324     0.208929
223        complete        NaN        NaN     0.214192     0.176429
233        complete        NaN        NaN     0.188411     0.158530
239        complete        NaN        NaN     0.215399     0.177062
245        complete   1.498603  38.555356     0.210205     0.173922
250        complete        NaN        NaN     0.184252     0.155551
252        complete   1.524000  35.381000     0.190766     0.160186
263        complete        NaN        NaN     0.226631     0.184606
269        complete   1.524003  43.091281     0.253960     0.202521
275        complete   1.574803  46.266428     0.205629     0.170409
276        complete        NaN        NaN     0.231706     0.188161
282        complete        NaN        NaN     0.180612     0.189118
292        complete        NaN        NaN     0.224997     0.183669
298      incomplete        NaN        NaN     0.215225     0.177128
301        complete        NaN        NaN     0.201458     0.167609
311      incomplete        NaN        NaN     0.222472     0.182038
317        complete        NaN        NaN     0.208755     0.172682
323        complete        NaN        NaN     0.224153     0.183085

     GM_percentage  WM_SC_ratio  WM_percentage
5        17.388181     0.826093      82.609278
11       17.787274     0.822528      82.252798
12       18.302606     0.817280      81.727999
18       15.271336     0.848863      84.886347
24       15.912704     0.841059      84.105917
34       17.657868     0.822950      82.295022
41       16.501533     0.835044      83.504351
47       17.522789     0.824820      82.481958
53       16.783009     0.832075      83.207456
59       17.992000     0.820054      82.005419
60       18.852976     0.811479      81.147943
67       16.694230     0.833104      83.310447
72       19.320039     0.806816      80.681582
78       16.809975     0.832266      83.226630
84       15.558455     0.844320      84.431970
90       16.693116     0.833116      83.311571
96       18.757648     0.813116      81.311588
102      18.275225     0.817240      81.723980
113      16.921450     0.831594      83.159364
119      18.560212     0.814498      81.449796
125      18.569550     0.815556      81.555631
126      17.773552     0.822532      82.253237
132      16.515063     0.834803      83.480315
139      15.251074     0.843332      84.333192
149      15.924922     0.840562      84.056161
155      15.664656     0.843593      84.359349
161      20.862054     0.791693      79.169321
162      18.216295     0.817478      81.747843
172      17.114076     0.828665      82.866501
179      23.410987     0.766255      76.625528
180      20.632579     0.793833      79.383345
186      21.105457     0.788891      78.889129
192      18.109452     0.818843      81.884341
198      17.041539     0.829580      82.957990
209      18.198856     0.817989      81.798881
215      16.908279     0.831101      83.110150
216      20.892894     0.793430      79.342991
223      17.642878     0.823694      82.369389
233      15.852972     0.841406      84.140554
239      17.706184     0.822017      82.201730
245      17.392196     0.827394      82.739370
250      15.555062     0.844228      84.422823
252      16.018560     0.839696      83.969573
263      18.460565     0.814563      81.456316
269      20.252143     0.797453      79.745301
275      17.040928     0.828723      82.872290
276      18.816111     0.812069      81.206935
282      18.911757     1.047091     104.709129
292      18.366900     0.816317      81.631672
298      17.712811     0.822989      82.298913
301      16.760895     0.831980      83.197954
311      18.203796     0.818250      81.824954
317      17.268172     0.827199      82.719878
323      18.308500     0.816786      81.678592

[54 rows x 90 columns]